#include <linux/init.h>
#include <linux/module.h>
#include <linux/cdev.h>
#include <linux/poll.h>
#include <linux/of_irq.h>
#include <linux/of_device.h>
#include <linux/spi/spi.h>
#include <linux/gpio/consumer.h>
#include <linux/delay.h>
#include <linux/interrupt.h>
#include <linux/kfifo.h>
#include <linux/wait.h>
#include <linux/uaccess.h>

#include "sx127x.h"
#include "sx127xlib.h"

#define DRV_NAME        "lora"
#define DRIVER_VER1		0					//
#define DRIVER_VER2		1					//
#define DRV_MAJOR		104 				//
#define DRV_MINOR	 	1					//

//debug macro
#undef	DEBUG
//#define DEBUG
#ifdef DEBUG
#define	DPRINTK( x... )		printk(DRV_NAME":" x)
#else
#define DPRINTK( x... )
#endif

#define XTAL_FREQ                                   32000000
#define FREQ_STEP                                   6103515625


/*!
 * \brief Radio hardware registers initialization definition
 *
 * \remark Can be automatically generated by the SX1276 GUI (not yet implemented)
 */
#define RADIO_INIT_REGISTERS_VALUE                \
{                                                 \
    { MODEM_FSK , REG_LNA                , 0x23 },\
    { MODEM_FSK , REG_RXCONFIG           , 0x1E },\
    { MODEM_FSK , REG_RSSICONFIG         , 0xD2 },\
    { MODEM_FSK , REG_AFCFEI             , 0x01 },\
    { MODEM_FSK , REG_PREAMBLEDETECT     , 0xAA },\
    { MODEM_FSK , REG_OSC                , 0x07 },\
    { MODEM_FSK , REG_SYNCCONFIG         , 0x12 },\
    { MODEM_FSK , REG_SYNCVALUE1         , 0xC1 },\
    { MODEM_FSK , REG_SYNCVALUE2         , 0x94 },\
    { MODEM_FSK , REG_SYNCVALUE3         , 0xC1 },\
    { MODEM_FSK , REG_PACKETCONFIG1      , 0xD8 },\
    { MODEM_FSK , REG_FIFOTHRESH         , 0x8F },\
    { MODEM_FSK , REG_IMAGECAL           , 0x02 },\
    { MODEM_FSK , REG_DIOMAPPING1        , 0x00 },\
    { MODEM_FSK , REG_DIOMAPPING2        , 0x30 },\
    { MODEM_LORA, REG_LR_PAYLOADMAXLENGTH, 0x40 },\
}                                     


/*!
 * Radio registers definition
 */
typedef struct
{
    RadioModems_t Modem;
    uint8_t       Addr;
    uint8_t       Value;
}RadioRegisters_t;

/*!
 * FSK bandwidth definition
 */
typedef struct
{
    uint32_t bandwidth;
    uint8_t  RegValue;
}FskBandwidth_t;

/*!
 * Radio hardware registers initialization
 *
 * \remark RADIO_INIT_REGISTERS_VALUE is defined in sx1276-board.h file
 */
const RadioRegisters_t RadioRegsInit[] = RADIO_INIT_REGISTERS_VALUE;



#define SX127X_DRIVERNAME	"sx127x"
#define SX127X_CLASSNAME	"sx127x"
#define SX127X_DEVICENAME	"sx127x%d"

#define SX127X_LORAREG_MASK BIT(8)
#define SX127X_LORAREG(addr) (addr | SX127X_LORAREG_MASK)
#define SX127X_FSKOOKREG_MASK BIT(9)
#define SX127X_FSKOOKREG(addr) (addr | SX127X_FSKOOK_MASK)

#define SX127X_REGADDR(reg) (reg & 0x7f)
#define SX127X_WRITEADDR(addr) (addr | (1 << 7))

#define SX127X_REG_FIFO													0x00

#define SX127X_REG_OPMODE												0x01
#define SX127X_REG_OPMODE_LONGRANGEMODE									BIT(7)
#define SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE							(BIT(6) | BIT(5))
#define SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE_FSK						0
#define SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE_OOK						BIT(5)
#define SX127X_REG_OPMODE_LOWFREQUENCYMODEON							BIT(3)
#define SX127X_REG_OPMODE_MODE											(BIT(2) | BIT(1) | BIT(0))
#define SX127X_REG_OPMODE_MODE_SLEEPMODE								0
#define SX127X_REG_OPMODE_MODE_STDBYMODE								BIT(0)

#define SX127X_REG_FSKOOK_BITRATEMSB									SX127X_FSKOOKREG(0x02)
#define SX127X_REG_FSKOOK_BITRATELSB									SX127X_FSKOOKREG(0x03)
#define SX127X_REG_FSKOOK_FDEVMSB										SX127X_FSKOOKREG(0x04)
#define SX127X_REG_FSKOOK_FDEVLSB										SX127X_FSKOOKREG(0x05)
#define SX127X_REG_FRFMSB												0x06
#define SX127X_REG_FRFMLD												0x07
#define SX127X_REG_FRFLSB												0x08

#define SX127X_REG_PACONFIG												0x09
#define SX127X_REG_PACONFIG_PASELECT									BIT(7)
#define SX127X_REG_PACONFIG_MAXPOWER									(BIT(6) | BIT(5) | BIT(4))
#define SX127X_REG_PACONFIG_MAXPOWER_SHIFT								4
#define SX127X_REG_PACONFIG_OUTPUTPOWER									(BIT(3) | BIT(2) | BIT(1) | BIT(0))

#define SX127X_REG_PARAMP												0x0a
#define SX127X_REG_OCP													0x0b
#define SX127X_REG_LNA													0x0c
#define SX127X_REG_FSKOOK_RXCONFIG										SX127X_FSKOOKREG(0x0d)
#define SX127X_REG_LORA_FIFOADDRPTR										SX127X_LORAREG(0x0d)
#define SX127X_REG_FSKOOK_RSSICONFIG									SX127X_FSKOOKREG(0x0e)
#define SX127X_REG_LORA_FIFOTXBASEADDR									SX127X_LORAREG(0x0e)
#define SX127X_REG_FSKOOK_RSSICOLLISION									SX127X_FSKOOKREG(0x0f)
#define SX127X_REG_LORA_RXBASEADDR										SX127X_LORAREG(0x0f)
#define SX127X_REG_FSKOOK_RSSTHRESH										SX127X_FSKOOKREG(0x10)
#define SX127X_REG_LORA_RXCURRENTADDR									SX127X_LORAREG(0x10)
#define SX127X_REG_FSKOOK_RSSIVALUE										SX127X_FSKOOKREG(0x11)
#define SX127X_REG_LORA_IRQMASKFLAGS									SX127X_LORAREG(0x11)
#define SX127X_REG_FSKOOK_RXBW											SX127X_FSKOOKREG(0x12)

#define SX127X_REG_LORA_IRQFLAGS										SX127X_LORAREG(0x12)
#define SX127X_REG_LORA_IRQFLAGS_RXTIMEOUT								BIT(7)
#define SX127X_REG_LORA_IRQFLAGS_RXDONE									BIT(6)
#define SX127X_REG_LORA_IRQFLAGS_PAYLOADCRCERROR						BIT(5)
#define SX127X_REG_LORA_IRQFLAGS_TXDONE									BIT(3)
#define SX127X_REG_LORA_IRQFLAGS_CADDONE								BIT(2)
#define SX127X_REG_LORA_IRQFLAGS_CADDETECTED							BIT(0)

#define SX127X_REG_FSKOOK_AFCBW											SX127X_FSKOOKREG(0x13)
#define SX127X_REG_LORA_RXNBBYTES										SX127X_LORAREG(0x13)
#define SX127X_REG_FSKOOK_OOKPEAK										SX127X_FSKOOKREG(0x14)
#define SX127X_REG_LORA_RXHEADERCNTVALUEMSB								SX127X_LORAREG(0x14)
#define SX127X_REG_FSKOOK_OOKFIX										SX127X_FSKOOKREG(0x15)
#define SX127X_REG_LORA_RXHEADERCNTVALUELSB								SX127X_LORAREG(0x15)
#define SX127X_REG_FSKOOK_OOKAVG										SX127X_FSKOOKREG(0x16)
#define SX127X_REG_LORA_RXPACKETCNTVALUEMSB								SX127X_LORAREG(0x16)
#define SX127X_REG_LORA_RXPACKETCNTVALUELSB								SX127X_LORAREG(0x17)
#define SX127X_REG_LORA_MODEMSTAT										SX127X_LORAREG(0x18)
#define SX127X_REG_LORA_PKTSNRVALUE										SX127X_LORAREG(0x19)
#define SX127X_REG_FSKOOK_AFCFEI										SX127X_FSKOOKREG(0x1a)
#define SX127X_REG_LORA_PKTRSSIVALUE									SX127X_LORAREG(0x1a)
#define SX127X_REG_FSKOOK_AFCMSB										SX127X_FSKOOKREG(0x1b)
#define SX127X_REG_LORA_RSSIVALUE										SX127X_LORAREG(0x1b)
#define SX127X_REG_FSKOOK_AFCLSB										SX127X_FSKOOKREG(0x1c)
#define SX127X_REG_LORA_HOPCHANNEL										SX127X_LORAREG(0x1c)
#define SX127X_REG_FSKOOK_FEIMSB										SX127X_FSKOOKREG(0x1d)

#define SX127X_REG_LORA_MODEMCONFIG1									SX127X_LORAREG(0x1d)
#define SX127X_REG_LORA_MODEMCONFIG1_BW									(BIT(7) | BIT(6) | BIT(5) | BIT(4))
#define SX127X_REG_LORA_MODEMCONFIG1_BW_SHIFT							4
#define SX127X_REG_LORA_MODEMCONFIG1_BW_MAX								9
#define SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE							(BIT(3) | BIT(2) | BIT(1))
#define SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_SHIFT					1
#define SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_MIN						1
#define SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_MAX						6
#define SX127X_REG_LORA_MODEMCONFIG1_IMPLICITHEADERMODEON				BIT(0)

#define SX127X_REG_FSKOOK_FEILSB										SX127X_FSKOOKREG(0x1e)

#define SX127X_REG_LORA_MODEMCONFIG2									SX127X_LORAREG(0x1e)
#define SX127X_REG_LORA_MODEMCONFIG2_SPREADINGFACTOR					(BIT(7) | BIT(6) | BIT(5) | BIT(4))
#define SX127X_REG_LORA_MODEMCONFIG2_SPREADINGFACTOR_SHIFT				4
#define SX127X_REG_LORA_MODEMCONFIG2_RXPAYLOADCRCON						BIT(2)

#define SX127X_REG_FSKOOK_PREAMBLEDETECT								SX127X_FSKOOKREG(0x1f)
#define SX127X_REG_LORA_SYMBTIMEOUTLSB									SX127X_LORAREG(0x1f)
#define SX127X_REG_FSKOOK_RXTIMEOUT1									SX127X_FSKOOKREG(0x20)
#define SX127X_REG_LORA_PREAMBLEMSB										SX127X_LORAREG(0x20)
#define SX127X_REG_FSKOOK_RXTIMEOUT2									SX127X_FSKOOKREG(0x21)
#define SX127X_REG_LORA_PREAMBLELSB										SX127X_LORAREG(0x21)
#define SX127X_REG_FSKOOK_RXTIMEOUT3									SX127X_FSKOOKREG(0x22)
#define SX127X_REG_LORA_PAYLOADLENGTH									SX127X_LORAREG(0x22)
#define SX127X_REG_FSKOOK_RXDELAY										SX127X_FSKOOKREG(0x23)
#define SX127X_REG_LORA_MAXPAYLOADLENGTH								SX127X_LORAREG(0x23)
#define SX127X_REG_FSKOOK_OSC											SX127X_FSKOOKREG(0x24)
#define SX127X_REG_LORA_HOPPERIOD										SX127X_LORAREG(0x24)
#define SX127X_REG_FSKOOK_PREAMBLEMSB									SX127X_FSKOOKREG(0x25)
#define SX127X_REG_LORA_FIFORXBYTEADDR									SX127X_LORAREG(0x25)
#define SX127X_REG_FSKOOK_PREAMBLELSB									SX127X_FSKOOKREG(0x26)

#define SX127X_REG_LORA_MODEMCONFIG3									SX127X_LORAREG(0x26)
#define SX127X_REG_LORA_MODEMCONFIG3_LOWDATARATEOPTIMIZE				BIT(3)

#define SX127X_REG_FSKOOK_SYNCCONFIG									SX127X_FSKOOKREG(0x27)
#define SX127X_REG_FSKOOK_SYNCVALUE1									SX127X_FSKOOKREG(0x28)
#define SX127X_REG_LORA_FEIMSB											SX127X_LORAREG(0x28)
#define SX127X_REG_FSKOOK_SYNCVALUE2									SX127X_FSKOOKREG(0x29)
#define SX127X_REG_LORA_FEIMID											SX127X_LORAREG(0x29)
#define SX127X_REG_FSKOOK_SYNCVALUE3									SX127X_FSKOOKREG(0x2a)
#define SX127X_REG_LORA_FEILSB											SX127X_LORAREG(0x29)
#define SX127X_REG_FSKOOK_SYNCVALUE4									SX127X_FSKOOKREG(0x2b)
#define SX127X_REG_FSKOOK_SYNCVALUE5									SX127X_FSKOOKREG(0x2c)
#define SX127X_REG_LORA_RSSIWIDEBAND									SX127X_LORAREG(0x2c)
#define SX127X_REG_FSKOOK_SYNCVALUE6									SX127X_FSKOOKREG(0x2d)
#define SX127X_REG_FSKOOK_SYNCVALUE7									SX127X_FSKOOKREG(0x2e)
#define SX127X_REG_FSKOOK_SYNCVALUE8									SX127X_FSKOOKREG(0x2f)
#define SX127X_REG_FSKOOK_PACKETCONFIG1									SX127X_FSKOOKREG(0x30)
#define SX127X_REG_FSKOOK_PACKETCONFIG2									SX127X_FSKOOKREG(0x31)

#define SX127X_REG_LORA_DETECTOPTIMIZATION								SX127X_LORAREG(0x31)
#define SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE			(BIT(2) | BIT(1) | BIT(0))
#define SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE_SF7SF12	0x03
#define SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE_SF6		0x05

#define SX127X_REG_FSKOOK_PAYLOADLENGTH									SX127X_FSKOOKREG(0x32)
#define SX127X_REG_FSKOOK_NODEADRS										SX127X_FSKOOKREG(0x33)
#define SX127X_REG_LORA_INVERTIQ										SX127X_LORAREG(0x33)
#define SX127X_REG_LORA_INVERTIQ_INVERTIQ								BIT(6)

#define SX127X_REG_FSKOOK_BROADCASTADRS									SX127X_FSKOOKREG(0x34)
#define SX127X_REG_FSKOOK_FIFOTHRESH									SX127X_FSKOOKREG(0x35)
#define SX127X_REG_FSKOOK_SEQCONFIG1									SX127X_FSKOOKREG(0x36)
#define SX127X_REG_FSKOOK_SEQCONFIG2									SX127X_FSKOOKREG(0x37)
#define SX127X_REG_LORA_DETECTIONTHRESHOLD								SX127X_LORAREG(0x37)
#define SX127X_REG_FSKOOK_TIMERRESOL									SX127X_FSKOOKREG(0x38)
#define SX127X_REG_FSKOOK_TIMER1COEF									SX127X_FSKOOKREG(0x39)
#define SX127X_REG_LORA_SYNCWORD										SX127X_LORAREG(0x39)
#define SX127X_REG_FSKOOK_TIMER2COEF									SX127X_FSKOOKREG(0x3a)
#define SX127X_REG_FSKOOK_IMAGECAL										SX127X_FSKOOKREG(0x3b)
#define SX127X_REG_FSKOOK_TEMP											SX127X_FSKOOKREG(0x3c)
#define SX127X_REG_FSKOOK_LOWBAT										SX127X_FSKOOKREG(0x3d)
#define SX127X_REG_FSKOOK_IRQFLAGS1										SX127X_FSKOOKREG(0x3e)
#define SX127X_REG_FSKOOK_IRQFLAGS2										SX127X_FSKOOKREG(0x3f)

#define SX127X_REG_DIOMAPPING1											0x40
#define SX127X_REG_DIOMAPPING1_DIO0										(BIT(7) | BIT(6))
#define SX127X_REG_DIOMAPPING1_DIO0_RXDONE								0
#define SX127X_REG_DIOMAPPING1_DIO0_TXDONE								(BIT(6))
#define SX127X_REG_DIOMAPPING1_DIO0_CADDONE								(BIT(7))

#define SX127X_REG_DIOMAPPING2											0x41
#define SX127X_REG_VERSION												0x42
#define SX127X_REG_FSKOOK_PLLHOP										SX127X_FSKOOKREG(0x44)
#define SX127X_REG_TCXO													0x4b
#define SX127X_REG_PADAC												0x4d
#define SX127X_REG_FORMERTEMP											0x5b
#define SX127X_REG_FSKOOK_BITRATEFRAC									SX127X_FSKOOKREG(0x5d)
#define SX127X_REG_AGCREF												0x61
#define SX127X_REG_AGCTHRESH1											0x62
#define SX127X_REG_AGCTHRESH2											0x63
#define SX127X_REG_AGCTHRESH3											0x64
#define SX127X_REG_PLL													0x70

static int devmajor;
static struct class *devclass;
static dev_t drv_dev_num = MKDEV(DRV_MAJOR, 0);
static struct cdev drv_cdev;
static struct class *drv_class;


static const char* invalid = "invalid";
static const char* modstr[] = {"fsk", "ook", "lora"};
static const char* opmodestr[] = {"sleep", "standby", "fstx", "tx", "fsrx", "rx", "rxcontinuous", "rxsingle", "cad"};
static unsigned bwmap[] = { 7800, 10400, 15600, 20800, 31250, 41700, 62500, 125000, 250000, 500000 };
static const char* paoutput[] = {"rfo", "pa_boost"};


static LIST_HEAD(device_list);
static DEFINE_MUTEX(device_list_lock);

static irqreturn_t sx127x_dio0_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio0_bottem_irq_thread(int irq, void *dev_id)
{
	//struct sx127x *data = container_of(work, struct sx127x, irq_work);
	struct sx127x *data = dev_id;
	u8 irqflags, buf[128], len, snr, rssi;
	u32 fei;
	struct sx127x_pkt pkt;
	mutex_lock(&data->mutex);
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_IRQFLAGS, &irqflags);
	if(irqflags & SX127X_REG_LORA_IRQFLAGS_RXDONE){
		dev_warn(data->chardevice, "reading packet\n");
		memset(&pkt, 0, sizeof(pkt));

		sx127x_fifo_readpkt(data->spidevice, buf, &len);
		sx127x_reg_read(data->spidevice, SX127X_REG_LORA_PKTSNRVALUE, &snr);
        if( SX1276.Settings.LoRaPacketHandler.SnrValue & 0x80 ) // The SNR sign bit is 1
        {
            // Invert and divide by 4
            snr = ( ( ~SX1276.Settings.LoRaPacketHandler.SnrValue + 1 ) & 0xFF ) >> 2;
            snr = -snr;
        }
        else
        {
            // Divide by 4
            snr = ( SX1276.Settings.LoRaPacketHandler.SnrValue & 0xFF ) >> 2;
        }
		sx127x_reg_read(data->spidevice, SX127X_REG_LORA_PKTRSSIVALUE, &rssi);
		sx127x_reg_read24(data->spidevice, SX127X_REG_LORA_FEIMSB, &fei);
		if( snr < 0 )
        {
            if( SX1276.Settings.Channel > RF_MID_BAND_THRESH )
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_HF + rssi + ( rssi >> 4 ) +
                                                              snr;
            }
            else
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_LF + rssi + ( rssi >> 4 ) +
                                                              snr;
            }
        }
        else
        {
            if( SX1276.Settings.Channel > RF_MID_BAND_THRESH )
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_HF + rssi + ( rssi >> 4 );
            }
            else
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_LF + rssi + ( rssi >> 4 );
            }
        }
		pkt.hdrlen = sizeof(pkt);
		pkt.payloadlen = len;
		pkt.len = pkt.hdrlen + pkt.payloadlen;
		pkt.snr = (__s16)(snr << 2) / 4 ;
		pkt.rssi = -157 + rssi; //TODO fix this for the LF port

		if(irqflags & SX127X_REG_LORA_IRQFLAGS_PAYLOADCRCERROR){
			dev_warn(data->chardevice, "CRC Error for received payload\n");
			pkt.crcfail = 1;
		}

		kfifo_in(&data->out, &pkt, sizeof(pkt));
		kfifo_in(&data->out, buf, len);
		wake_up(&data->readwq);
	}
	else if(irqflags & SX127X_REG_LORA_IRQFLAGS_TXDONE){
		if(data->gpio_txen){
			gpiod_set_value(data->gpio_txen, 0);
		}
		dev_warn(data->chardevice, "transmitted packet\n");
		/* after tx the chip goes back to standby so restore the user selected mode if it wasn't standby */
		if(data->opmode != SX127X_OPMODE_STANDBY){
			dev_info(data->chardevice, "restoring opmode\n");
			sx127x_setopmode(data, data->opmode, false);
		}
		data->transmitted = 1;
		wake_up(&data->writewq);
	}
	else if(irqflags & SX127X_REG_LORA_IRQFLAGS_CADDONE){
		if(irqflags & SX127X_REG_LORA_IRQFLAGS_CADDETECTED){
			dev_info(data->chardevice, "CAD done, detected activity\n");
		}
		else {
			dev_info(data->chardevice, "CAD done, nothing detected\n");
		}
	}
	else {
		dev_err(&data->spidevice->dev, "unhandled interrupt state %02x\n", (unsigned) irqflags);
	}
	sx127x_reg_write(data->spidevice, SX127X_REG_LORA_IRQFLAGS, 0xff);
	mutex_unlock(&data->mutex);
    enable_irq(irq);

	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio1_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio1_bottem_irq_thread(int irq, void *dev_id)
{
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio2_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio2_bottem_irq_thread(int irq, void *dev_id)
{
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio3_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio3_bottem_irq_thread(int irq, void *dev_id)
{
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio4_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_dio4_bottem_irq_thread(int irq, void *dev_id)
{
	return IRQ_HANDLED;
}


static int sx127x_io_init(struct sx127x_platform_data *plat_data_ptr)
{
    int result = 0;
    
    if(NULL == plat_data_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
   
    if(IS_ERR(plat_data_ptr->gpio_dio0))
    {
        result = gpiod_request(plat_data_ptr->gpio_dio0, "dio0");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request DIO0 error\n");
            goto ERR_EXIT;
        }
    }

    if(IS_ERR(plat_data_ptr->gpio_dio1))
    {
        result = gpiod_request(plat_data_ptr->gpio_dio1, "dio1");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request DIO1 error\n");
            goto ERR_EXIT1;
        }
    }

    if(IS_ERR(plat_data_ptr->gpio_dio2))
    {
        result = gpiod_request(plat_data_ptr->gpio_dio2, "dio2");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request DIO2 error\n");
            goto ERR_EXIT2;
        }
    }

    if(IS_ERR(plat_data_ptr->gpio_dio3))
    {
        result = gpiod_request(plat_data_ptr->gpio_dio3, "dio3");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request DIO3 error\n");
            goto ERR_EXIT3;
        }
    }

    if(IS_ERR(plat_data_ptr->gpio_dio4))
    {
        result = gpiod_request(plat_data_ptr->gpio_dio4, "dio4");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request DIO4 error\n");
            goto ERR_EXIT4;
        }
    }

    if(IS_ERR(plat_data_ptr->gpio_reset))
    {
        result = gpiod_request(plat_data_ptr->gpio_reset, "reset");
        if(result < 0)
        {
            printk(KERN_ERR "gpio_request RESET error\n");
            goto ERR_EXIT5;
        }
    }

    return result;
ERR_EXIT5:
    if(IS_ERR(plat_data_ptr->gpio_dio4))
        gpiod_free(plat_data_ptr->gpio_dio4);
ERR_EXIT4:
    if(IS_ERR(plat_data_ptr->gpio_dio3))
        gpiod_free(plat_data_ptr->gpio_dio3);
ERR_EXIT3:
    if(IS_ERR(plat_data_ptr->gpio_dio2))
        gpiod_free(plat_data_ptr->gpio_dio2);
ERR_EXIT2:
    if(IS_ERR(plat_data_ptr->gpio_dio1))
        gpiod_free(plat_data_ptr->gpio_dio1);
ERR_EXIT1:
    if(IS_ERR(plat_data_ptr->gpio_dio0))
        gpiod_free(plat_data_ptr->gpio_dio0);
ERR_EXIT:
    return result;
}

int sx127x_irq_init(struct sx127x *sx127x_ptr)
{
    int irq = 0;
    int ret = 0;

    if(NULL == sx127x_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT0;
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio0)
    {
    	ret = devm_request_threaded_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio0, sx127x_dio0_top_irq_handler, 
										sx127x_dio0_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, sx127x_ptr);
	    if(ret < 0)
	    {
	        goto ERR_EXIT0;
	    }
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio1)
    {
    	ret = devm_request_threaded_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio1, sx127x_dio1_top_irq_handler, 
										sx127x_dio1_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, sx127x_ptr);

        if(ret)     
        {       
            printk(KERN_ERR "%s %d request_irq ERROR\n", __FUNCTION__, __LINE__);
            ret = -EFAULT;
            goto ERR_EXIT1; 
        }
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio2)
    {
        ret = devm_request_threaded_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio2, sx127x_dio2_top_irq_handler, 
										sx127x_dio2_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, sx127x_ptr);
        if(ret)     
        {       
            printk(KERN_ERR "%s %d request_irq ERROR\n", __FUNCTION__, __LINE__);
            ret = -EFAULT;
            goto ERR_EXIT2; 
        }
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio3)
    {
        ret = devm_request_threaded_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio3, sx127x_dio3_top_irq_handler, 
										sx127x_dio3_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, sx127x_ptr);
        if(ret)     
        {       
            printk(KERN_ERR "%s %d request_irq ERROR\n", __FUNCTION__, __LINE__);
            ret = -EFAULT;
            goto ERR_EXIT3; 
        }
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio4)
    {
        ret = devm_request_threaded_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio4, sx127x_dio4_top_irq_handler, 
										sx127x_dio4_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, sx127x_ptr);
        if(ret)     
        {       
            printk(KERN_ERR "%s %d request_irq ERROR\n", __FUNCTION__, __LINE__);
            ret = -EFAULT;
            goto ERR_EXIT4; 
        }
    }

    return ret;

ERR_EXIT4:
    if(sx127x_ptr->plat_data.irq_gpio_dio3)
    {
        devm_free_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio3, sx127x_ptr);    
    }
ERR_EXIT3:
    if(sx127x_ptr->plat_data.irq_gpio_dio2)
    {
        devm_free_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio2, sx127x_ptr);
    }
ERR_EXIT2:
    if(sx127x_ptr->plat_data.irq_gpio_dio1)
    {
        devm_free_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio1, sx127x_ptr);
    }
ERR_EXIT1:
    if(sx127x_ptr->plat_data.irq_gpio_dio0)
    {
        devm_free_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio0, sx127x_ptr);
    }
ERR_EXIT0:
	
    return ret;
}

int sx127x_io_deinit(struct sx127x_platform_data *plat_data_ptr)
{
    int result = 0;

    if(NULL == plat_data_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    if(IS_ERR(plat_data_ptr->gpio_dio0))
    {
        gpiod_free(plat_data_ptr->gpio_dio0);
    }
    
    if(IS_ERR(plat_data_ptr->gpio_dio1))
    {
        gpiod_free(&plat_data_ptr->gpio_dio0);
    }

    if(IS_ERR(plat_data_ptr->gpio_dio2))
    {
        gpiod_free(plat_data_ptr->gpio_reset);
    }

    if(IS_ERR(plat_data_ptr->gpio_dio3))
    {
        gpiod_free(plat_data_ptr->gpio_reset);
    }

    if(IS_ERR(plat_data_ptr->gpio_dio4))
    {
        gpiod_free(plat_data_ptr->gpio_reset);
    }
   
    if(IS_ERR(plat_data_ptr->gpio_reset))
    {
        gpiod_free(plat_data_ptr->gpio_reset);
    }
	
ERR_EXIT:

    return result;
}

int sx127x_irq_deinit(struct sx127x *sx127x_ptr)
{
    int irq = 0;
    int result = 0;

    if(NULL == sx127x_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio0)
    {
        devm_free_irq(sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio0, sx127x_ptr);
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio1)
    {
       devm_free_irq(sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio1, sx127x_ptr);
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio2)
    {
        devm_free_irq(sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio2, sx127x_ptr);
    }

    if(sx127x_ptr->plat_data.irq_gpio_dio3)
    {
        devm_free_irq(sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio3, sx127x_ptr);
    }
    
    if(sx127x_ptr->plat_data.irq_gpio_dio4)
    {
        devm_free_irq(&sx127x_ptr->dev, sx127x_ptr->plat_data.irq_gpio_dio4, sx127x_ptr);
    }
ERR_EXIT:
    
    return result;
}


static int sx127x_parse_dt(struct device *dev_ptr, struct sx127x_platform_data *platdata_ptr)
{
    int result = 0;

    if ((NULL == node_ptr) || (NULL == platdata_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    platdata_ptr->gpio_dio0 = devm_gpiod_get(dev_ptr, "dio0-gpios");
    platdata_ptr->gpio_dio1 = devm_gpiod_get(dev_ptr, "dio1-gpios");
    platdata_ptr->gpio_dio2 = devm_gpiod_get(dev_ptr, "dio2-gpios");
    platdata_ptr->gpio_dio3 = devm_gpiod_get(dev_ptr, "dio3-gpios");
    platdata_ptr->gpio_dio4 = devm_gpiod_get(dev_ptr, "dio4-gpios");
    platdata_ptr->gpio_reset= devm_gpiod_get(dev_ptr, "reset-gpios");

	if(IS_ERR(platdata_ptr->gpio_dio0))
    {
        platdata_ptr->irq_dio0 = gpiod_to_irq(platdata_ptr->gpio_dio0);
    }

    if(IS_ERR(platdata_ptr->gpio_dio1))
    {
        platdata_ptr->irq_dio1 = gpiod_to_irq(platdata_ptr->gpio_dio1);
    }

    if(IS_ERR(platdata_ptr->gpio_dio2))
    {
        platdata_ptr->irq_dio2 = gpiod_to_irq(platdata_ptr->gpio_dio2);
    }

    if(IS_ERR(platdata_ptr->gpio_dio3))
    {
        platdata_ptr->irq_dio3 = gpiod_to_irq(platdata_ptr->gpio_dio3);
    }

    if(IS_ERR(platdata_ptr->gpio_dio4))
    {
        platdata_ptr->irq_dio4 = gpiod_to_irq(platdata_ptr->gpio_dio4);
    }

    
ERR_EXIT:

    return result;
}

static int sx127x_reg_read(struct spi_device *spi, u16 reg, u8* result){
	u8 addr = reg & 0xff;
	int ret = spi_write_then_read(spi,
			&addr, 1,
			result, 1);
	dev_dbg(&spi->dev, "read: @%02x %02x\n", addr, *result);
	return ret;
}

static int sx127x_reg_read16(struct spi_device *spi, u16 reg, u16* result){
	u8 addr = reg & 0xff;
	int ret = spi_write_then_read(spi,
			&addr, 1,
			result, 2);
	dev_dbg(&spi->dev, "read: @%02x %02x\n", addr, *result);
	return ret;
}

static int sx127x_reg_read24(struct spi_device *spi, u16 reg, u32* result){
	u8 addr = reg & 0xff, buf[3];
	int ret = spi_write_then_read(spi,
			&addr, 1,
			buf, 3);
	*result = (buf[0] << 16) | (buf[1] << 8) | buf[0];
	dev_dbg(&spi->dev, "read: @%02x %06x\n", addr, *result);
	return ret;
}

static int sx127x_reg_write(struct spi_device *spi, u16 reg, u8 value){
	u8 addr = SX127X_REGADDR(reg), buff[2];//, readback;
	int ret;
	buff[0] = SX127X_WRITEADDR(addr);
	buff[1] = value;
	dev_dbg(&spi->dev, "write: @%02x %02x\n", addr, value);
	ret = spi_write(spi, buff, 2);
//	ret = sx127x_reg_read(spi, reg, &readback);
//	if(readback != value){
//		dev_warn(&spi->dev, "read back does not match\n");
//	}
	return ret;
}

static int sx127x_reg_write24(struct spi_device *spi, u16 reg, u32 value){
	u8 addr = SX127X_REGADDR(reg), buff[4];
	int ret;
	buff[0] = SX127X_WRITEADDR(addr);
	buff[1] = (value >> 16) & 0xff;
	buff[2] = (value >> 8) & 0xff;
	buff[3] = value & 0xff;
	dev_dbg(&spi->dev, "write: @%02x %06x\n", addr, value);
	ret = spi_write(spi, buff, sizeof(buff));
	return ret;
}

static int sx127x_fifo_readpkt(struct spi_device *spi, void *buffer, u8 *len){
	u8 addr = SX127X_REG_FIFO, pktstart, rxbytes, off, fifoaddr;
	size_t maxtransfer = 0xFFFFFFFF;//spi_max_transfer_size(spi);
	int ret;
	unsigned readlen;
	ret = sx127x_reg_read(spi, SX127X_REG_LORA_RXCURRENTADDR, &pktstart);
	ret = sx127x_reg_read(spi, SX127X_REG_LORA_RXNBBYTES, &rxbytes);
	for(off = 0; off < rxbytes; off += maxtransfer){
		readlen = min(maxtransfer, (size_t) (rxbytes - off));
		fifoaddr = pktstart + off;
		ret = sx127x_reg_write(spi, SX127X_REG_LORA_FIFOADDRPTR, fifoaddr);
		if(ret){
			break;
		}
		dev_warn(&spi->dev, "fifo read: %02x from %02x\n", readlen, fifoaddr);
		ret = spi_write_then_read(spi,
				&addr, 1,
				buffer + off, readlen);
		if(ret){
			break;
		}

	}
	print_hex_dump_bytes("", DUMP_PREFIX_NONE, buffer, rxbytes);
	*len = rxbytes;
	return ret;
}

static int sx127x_fifo_writepkt(struct spi_device *spi, void *buffer, u8 len){
	u8 addr = SX127X_WRITEADDR(SX127X_REGADDR(SX127X_REG_FIFO));
	int ret;
	struct spi_transfer fifotransfers[] = {
			{.tx_buf = &addr, .len = 1},
			{.tx_buf = buffer, .len = len},
	};

	u8 readbackaddr = SX127X_REGADDR(SX127X_REG_FIFO);
	u8 readbackbuff[256];
	struct spi_transfer readbacktransfers[] = {
			{.tx_buf = &readbackaddr, .len = 1},
			{.rx_buf = &readbackbuff, .len = len},
	};

	ret = sx127x_reg_write(spi, SX127X_REG_LORA_FIFOTXBASEADDR, 0);
	ret = sx127x_reg_write(spi, SX127X_REG_LORA_FIFOADDRPTR, 0);
	ret = sx127x_reg_write(spi, SX127X_REG_LORA_PAYLOADLENGTH, len);

	dev_info(&spi->dev, "fifo write: %d\n", len);
	print_hex_dump(KERN_DEBUG, NULL, DUMP_PREFIX_NONE, 16, 1, buffer, len, true);
	spi_sync_transfer(spi, fifotransfers, ARRAY_SIZE(fifotransfers));

	ret = sx127x_reg_write(spi, SX127X_REG_LORA_FIFOADDRPTR, 0);
	spi_sync_transfer(spi, readbacktransfers, ARRAY_SIZE(readbacktransfers));
	if(memcmp(buffer, readbackbuff, len) != 0){
		dev_err(&spi->dev, "fifo readback doesn't match\n");
	}
	return ret;
}

int sx127x_reset(struct sx127x_platform_data *platdata_ptr)
{
	int ret = 0;

	if(NULL == platdata_ptr)
	{
		ret = -ENOMEM;
		goto error;
	}

	gpiod_set_value(platdata_ptr->gpio_reset, 1);
	
	mdelay(1);
	
	gpiod_set_value(platdata_ptr->gpio_reset, 0);
	
	mdelay(6);

	return ret;
}

static int sx127x_set_freq(struct sx127x *sx127x_ptr, u32 freq)
{
	int ret = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);
	u64 temp_freq = 0;
	u64 freq_step = FREQ_STEP;
	u32 temp_freq_step;
	
	do_div(temp_freq_step, 5);   
    temp_freq_step = (u32)freq_step;
 
    temp_freq = (u64)freq * 100000000;
    do_div(temp_freq, temp_freq_step);
    
    freq = ( u32 )temp_freq / 5;
	
    ret = sx127x_reg_write(spi, REG_FRFMSB, (u8)((freq >> 16) & 0xFF));
	
    ret = sx127x_reg_write(spi, REG_FRFMID, (u8)((freq >> 8) & 0xFF));
	
    ret = sx127x_reg_write(spi, REG_FRFLSB, (u8)(freq & 0xFF));
	
	return ret;
}

static int sx127x_set_opmode(struct sx127x *sx127x_ptr, u8 opMode)
{
	int ret = 0;
	u8 reg = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);
	
    if( opMode == RF_OPMODE_SLEEP )
    {
        //SX1276SetAntSwLowPower( true );
    }
    else
    {
        //SX1276SetAntSwLowPower( false );
        //SX1276SetAntSw( opMode );
    }

	sx127x_reg_read(spi, REG_OPMODE, &reg);
	
    sx127x_reg_write(spi, REG_OPMODE, ((reg&RF_OPMODE_MASK)|opMode));

	return ret;
}

static int sx127x_set_sleep(struct sx127x *sx127x_ptr)
{
	int ret = 0;
	
	sx127x_set_opmode(sx127x_ptr, RF_OPMODE_SLEEP);

	return ret;
}

static int sx127x_set_stby(struct sx127x *sx127x_ptr)
{
	int ret = 0;

    sx127x_set_opmode( RF_OPMODE_STANDBY );

	return ret;
}

static int sx127x_set_modem(struct sx127x *sx127x_ptr, RadioModems_t modem)
{
	u8 reg = 0;
	int ret = 0;
	RadioModems_t curmodem;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);

	ret = sx127x_reg_read(spi, REG_OPMODE, &reg);
    if((reg&RFLR_OPMODE_LONGRANGEMODE_ON) != 0)
    {
        curmodem = MODEM_LORA;
    }
    else
    {
        curmodem = MODEM_FSK;
    }

    if(curmodem == modem )
    {
        return ;
    }

    switch(modem)
    {
    default:
    case MODEM_FSK:
        sx127x_set_sleep();
		ret = sx127x_reg_read(spi, REG_OPMODE, &reg);
        sx127x_reg_write(spi, REG_OPMODE, (reg&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_OFF);

        sx127x_reg_write(spi, REG_DIOMAPPING1, 0x00);
        sx127x_reg_write(spi, REG_DIOMAPPING2, 0x30); // DIO5=ModeReady
        break;
    case MODEM_LORA:
        sx127x_set_sleep( );
		ret = sx127x_reg_read(spi, REG_OPMODE, &reg);
        sx127x_reg_write(spi, REG_OPMODE, (reg&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_ON);

        sx127x_reg_write(spi, REG_DIOMAPPING1, 0x00 );
        sx127x_reg_write(spi, REG_DIOMAPPING2, 0x00 );
        break;
    }

	return ret;
}

/*!
 * Performs the Rx chain calibration for LF and HF bands
 * \remark Must be called just after the reset so all registers are at their
 *         default values
 */
static int RxChainCalibration(struct sx127x *sx127x_ptr)
{
	int result = 0;
	uint8_t regval0 = 0, regval1 = 0, regval2 = 0;
	uint8_t regPaConfigInitVal = 0;
	uint32_t initialFreq = 0;
	uint64_t temp = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);

	// Save context
	result = sx127x_reg_read(spi, REG_PACONFIG, &regPaConfigInitVal);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	result = sx127x_reg_read(spi, REG_FRFMSB, &regval0);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	
	result = sx127x_reg_read(spi, REG_FRFMID, &regval1);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	
	result = sx127x_reg_read(spi, REG_FRFLSB, &regval2);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	temp = (((uint32_t)regval0 << 16) | ((uint32_t)regval1 << 8) | (uint32_t)regval2) * FREQ_STEP;

	do_div(temp, 100000000);

	initialFreq = (uint32_t)temp;

	// Cut the PA just in case, RFO output, power = -1 dBm
	result = sx127x_reg_write(spi, REG_PACONFIG, 0x00);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	// Launch Rx chain calibration for LF band
	result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	result = sx127x_reg_write(spi, REG_IMAGECAL, (regval0 & RF_IMAGECAL_IMAGECAL_MASK)|RF_IMAGECAL_IMAGECAL_START);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	while((regval0&RF_IMAGECAL_IMAGECAL_RUNNING) == RF_IMAGECAL_IMAGECAL_RUNNING)
	{
		result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
		if(result < 0)
		{
			goto ERR_EXIT;
		}
	}

	// Sets a Frequency in HF band
	result = sx127x_set_freq(sx127x_ptr, 868000000);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	// Launch Rx chain calibration for HF band
	result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	
	result = sx127x_reg_write(spi, REG_IMAGECAL, (regval0 &RF_IMAGECAL_IMAGECAL_MASK)|RF_IMAGECAL_IMAGECAL_START);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

	result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	
	while((regval0&RF_IMAGECAL_IMAGECAL_RUNNING) == RF_IMAGECAL_IMAGECAL_RUNNING)
	{
		result = sx127x_reg_read(spi, REG_IMAGECAL, &regval0);
		if(result < 0)
		{
			goto ERR_EXIT;
		}
	}

	// Restore context
	result = sx127x_reg_write(spi, REG_PACONFIG, regPaConfigInitVal);
	if(result < 0)
	{
		goto ERR_EXIT;
	}
	
	result = sx127x_set_freq(sx127x_ptr, initialFreq);
	if(result < 0)
	{
		goto ERR_EXIT;
	}

ERR_EXIT:

	return result;
}


#define RF_MID_BAND_THRESH                          525000000

u8 sx127x_get_paselect(u32 channel)
{
    if(channel < RF_MID_BAND_THRESH)
    {
        return RF_PACONFIG_PASELECT_PABOOST;
    }
    else
    {
        return RF_PACONFIG_PASELECT_RFO;
    }
}

int sx127x_set_txpower(struct sx127x *sx127x_ptr, uint32_t freq, int power)
{
    int result = 0;
    u8 paConfig = 0;
    u8 paDac = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);

    result = sx127x_reg_read(spi ,REG_PACONFIG, &paConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = sx127x_reg_read(spi ,REG_PADAC, &paDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    paConfig = ( paConfig & RF_PACONFIG_PASELECT_MASK ) | sx127x_get_paselect(freq);
    paConfig = ( paConfig & RF_PACONFIG_MAX_POWER_MASK ) | 0x70;

    if( ( paConfig & RF_PACONFIG_PASELECT_PABOOST ) == RF_PACONFIG_PASELECT_PABOOST )
    {
        if( power > 17 )
        {
            paDac = ( paDac & RF_PADAC_20DBM_MASK ) | RF_PADAC_20DBM_ON;
        }
        else
        {
            paDac = ( paDac & RF_PADAC_20DBM_MASK ) | RF_PADAC_20DBM_OFF;
        }
        if( ( paDac & RF_PADAC_20DBM_ON ) == RF_PADAC_20DBM_ON )
        {
            if( power < 5 )
            {
                power = 5;
            }
            if( power > 20 )
            {
                power = 20;
            }
            paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( u8 )( ( u16 )( power - 5 ) & 0x0F );
        }
        else
        {
            if( power < 2 )
            {
                power = 2;
            }
            if( power > 17 )
            {
                power = 17;
            }
            paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( u8 )( ( u16 )( power - 2 ) & 0x0F );
        }
    }
    else
    {
        if( power < -1 )
        {
            power = -1;
        }
        if( power > 14 )
        {
            power = 14;
        }
        paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( u8 )( ( u16 )( power + 1 ) & 0x0F );
    }
    result = sx127x_reg_write(spi, REG_PACONFIG, paConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = sx127x_reg_write(spi, REG_PADAC, paDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}


int sx127x_init(struct sx127x *sx127x_ptr)
{
	int ret = 0;
    uint8_t i;

	if(NULL == sx127x_ptr)
	{
		ret = -ENOMEM;
		goto error;
	}

	sx127x_io_init(&sx127x_ptr->plat_data);
	
    ret = sx127x_reset(&sx127x_ptr->plat_data);
	if(ret < 0)
	{
		goto error;
	}

    RxChainCalibration(sx127x_ptr);

    sx127x_set_opmode(RF_OPMODE_SLEEP);

    sx127x_irq_init(sx127x_ptr);

    for(i = 0; i < sizeof(RadioRegsInit) / sizeof(RadioRegisters_t); i++)
    {
        sx127x_set_modem(RadioRegsInit[i].Modem);
        sx127x_reg_write(RadioRegsInit[i].Addr, RadioRegsInit[i].Value);
    }

    sx127x_set_modem(sx127x_ptr, MODEM_FSK);

    sx127x_ptr.cfg.State = RF_IDLE;

error:

	return ret;
}



void sx127x_set_rxconfig(struct sx127x *sx127x_ptr)
{
	int ret = 0;
	u8 reg = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);
	RadioModems_t modem = sx127x_ptr->cfg.Modem;
	u32 freq = sx127x_ptr->cfg.LoRa.rChannel;
	
    sx127x_set_modem(sx127x_ptr, modem);

	sx127x_set_freq(sx127x_ptr, freq);

    switch(modem)
    {
    case MODEM_FSK:
        break;
    case MODEM_LORA:
        {
			bool fixLen = 0;
			u16 payloadLen = 0;
			u32 bandwidth = sx127x_ptr->cfg.LoRa.rBandwidth;
			u32 datarate = sx127x_ptr->cfg.LoRa.rDatarate;
			u8 coderate = sx127x_ptr->cfg.LoRa.rCoderate;
			u8 HopPeriod = sx127x_ptr->cfg.LoRa.HopPeriod;
			u8 symbTimeout = 5;
			u16 preambleLen = sx127x_ptr->cfg.LoRa.PreambleLen;
			bool crcOn = sx127x_ptr->cfg.LoRa.CrcOn;
			u8 LowDatarateOptimize = 0;
			
            if( ( ( bandwidth == 7 ) && ( ( datarate == 11 ) || ( datarate == 12 ) ) ) ||
                ( ( bandwidth == 8 ) && ( datarate == 12 ) ) )
            {
                LowDatarateOptimize = 0x01;
            }
            else
            {
                LowDatarateOptimize = 0x00;
            }


			sx127x_reg_read(spi, REG_LR_MODEMCONFIG1, &reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG1,
                         ( reg &
                           RFLR_MODEMCONFIG1_BW_MASK &
                           RFLR_MODEMCONFIG1_CODINGRATE_MASK &
                           RFLR_MODEMCONFIG1_IMPLICITHEADER_MASK ) |
                           ( bandwidth << 4 ) | ( coderate << 1 ) |
                           fixLen );

			sx127x_reg_read(spi, REG_LR_MODEMCONFIG2, &reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG2,
                         ( reg &
                           RFLR_MODEMCONFIG2_SF_MASK &
                           RFLR_MODEMCONFIG2_RXPAYLOADCRC_MASK &
                           RFLR_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK ) |
                           ( datarate << 4 ) | ( crcOn << 2 ) |
                           ( ( symbTimeout >> 8 ) & ~RFLR_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK ) );

			sx127x_reg_read(spi, REG_LR_MODEMCONFIG3, reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG3,
                         ( reg &
                           RFLR_MODEMCONFIG3_LOWDATARATEOPTIMIZE_MASK ) |
                           ( LowDatarateOptimize << 3 ) );

            sx127x_reg_write(spi, REG_LR_SYMBTIMEOUTLSB, ( u8 )( symbTimeout & 0xFF ) );

            sx127x_reg_write(spi, REG_LR_PREAMBLEMSB, ( u8 )( ( preambleLen >> 8 ) & 0xFF ) );
            sx127x_reg_write(spi, REG_LR_PREAMBLELSB, ( u8 )( preambleLen & 0xFF ) );

            if( fixLen == 1 )
            {
                sx127x_reg_write(spi, REG_LR_PAYLOADLENGTH, payloadLen );
            }

            if( SX1276.Settings.LoRa.FreqHopOn == true )
            {
            	sx127x_reg_read(spi, REG_LR_PLLHOP, &reg);
                sx127x_reg_write(spi, REG_LR_PLLHOP, ( reg & RFLR_PLLHOP_FASTHOP_MASK ) | RFLR_PLLHOP_FASTHOP_ON );
                sx127x_reg_write(spi, REG_LR_HOPPERIOD, HopPeriod );
            }

            if( ( bandwidth == 9 ) && ( SX1276.Settings.Channel > RF_MID_BAND_THRESH ) )
            {
                // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
                sx127x_reg_write(spi, REG_LR_TEST36, 0x02);
                sx127x_reg_write(spi, REG_LR_TEST3A, 0x64);
            }
            else if( bandwidth == 9 )
            {
                // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
                sx127x_reg_write(spi, REG_LR_TEST36, 0x02);
                sx127x_reg_write(spi, REG_LR_TEST3A, 0x7F);
            }
            else
            {
                // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
                sx127x_reg_write(spi, REG_LR_TEST36, 0x03);
            }

            if( datarate == 6 )
            {
            	sx127x_reg_read(spi, REG_LR_DETECTOPTIMIZE, &reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE,
                             (reg  &
                               RFLR_DETECTIONOPTIMIZE_MASK ) |
                               RFLR_DETECTIONOPTIMIZE_SF6 );
                sx127x_reg_write(spi, REG_LR_DETECTIONTHRESHOLD,
                             RFLR_DETECTIONTHRESH_SF6 );
            }
            else
            {
            	sx127x_reg_read(spi, REG_LR_DETECTOPTIMIZE, &reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE,
                             ( reg &
                             RFLR_DETECTIONOPTIMIZE_MASK ) |
                             RFLR_DETECTIONOPTIMIZE_SF7_TO_SF12 );
                sx127x_reg_write(spi, REG_LR_DETECTIONTHRESHOLD,
                             RFLR_DETECTIONTHRESH_SF7_TO_SF12 );
            }
        }
        break;
    }

	return ret;
}



void sx127x_set_txconfig(struct sx127x *sx127x_ptr)
{
	int ret = 0;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);
	RadioModems_t modem = sx127x_ptr->cfg.Modem;
	u32 freq = sx127x_ptr->cfg.LoRa.tChannel;

    sx127x_set_modem(sx127x_ptr, modem);

	sx127x_set_freq(sx127x_ptr, freq);

    sx127x_set_txpower(sx127x_ptr, power);

    switch( modem )
    {
    case MODEM_FSK:
        {
#if 0			
            SX1276.Settings.Fsk.Power = power;
            SX1276.Settings.Fsk.Fdev = fdev;
            SX1276.Settings.Fsk.Bandwidth = bandwidth;
            SX1276.Settings.Fsk.Datarate = datarate;
            SX1276.Settings.Fsk.PreambleLen = preambleLen;
            SX1276.Settings.Fsk.FixLen = fixLen;
            SX1276.Settings.Fsk.CrcOn = crcOn;
            SX1276.Settings.Fsk.IqInverted = iqInverted;
            SX1276.Settings.Fsk.TxTimeout = timeout;

            fdev = ( uint16_t )( ( double )fdev / ( double )FREQ_STEP );
            SX1276Write( REG_FDEVMSB, ( uint8_t )( fdev >> 8 ) );
            SX1276Write( REG_FDEVLSB, ( uint8_t )( fdev & 0xFF ) );

            datarate = ( uint16_t )( ( double )XTAL_FREQ / ( double )datarate );
            SX1276Write( REG_BITRATEMSB, ( uint8_t )( datarate >> 8 ) );
            SX1276Write( REG_BITRATELSB, ( uint8_t )( datarate & 0xFF ) );

            SX1276Write( REG_PREAMBLEMSB, ( preambleLen >> 8 ) & 0x00FF );
            SX1276Write( REG_PREAMBLELSB, preambleLen & 0xFF );

            SX1276Write( REG_PACKETCONFIG1,
                         ( SX1276Read( REG_PACKETCONFIG1 ) &
                           RF_PACKETCONFIG1_CRC_MASK &
                           RF_PACKETCONFIG1_PACKETFORMAT_MASK ) |
                           ( ( fixLen == 1 ) ? RF_PACKETCONFIG1_PACKETFORMAT_FIXED : RF_PACKETCONFIG1_PACKETFORMAT_VARIABLE ) |
                           ( crcOn << 4 ) );
            SX1276Write( REG_PACKETCONFIG2, ( SX1276Read( REG_PACKETCONFIG2 ) | RF_PACKETCONFIG2_DATAMODE_PACKET ) );
#endif			
        }
        break;
    case MODEM_LORA:
        {
			u8 reg = 0;
			s8 power = sx127x_ptr->cfg.LoRa.Power;
			u32 freq = sx127x_ptr->cfg.LoRa.tChannel;
			u32 bandwidth = sx127x_ptr->cfg.LoRa.tBandwidth;
			u32 datarate = sx127x_ptr->cfg.LoRa.tDatarate;
			u8 coderate = sx127x_ptr->cfg.LoRa.tCoderate;
			bool freqHopOn = sx127x_ptr->cfg.LoRa.FreqHopOn;
			s8 hopPeriod = sx127x_ptr->cfg.LoRa.HopPeriod;
			bool fixlen = sx127x_ptr->cfg.LoRa.FixLen;
			bool crcOn = sx127x_ptr->cfg.LoRa.CrcOn;
			u16 preambleLen = sx127x_ptr->cfg.LoRa.PreambleLen;
            if( datarate > 12 )
            {
                datarate = 12;
            }
            else if( datarate < 6 )
            {
                datarate = 6;
            }
            if( ( ( bandwidth == 7 ) && ( ( datarate == 11 ) || ( datarate == 12 ) ) ) ||
                ( ( bandwidth == 8 ) && ( datarate == 12 ) ) )
            {
                sx127x_ptr->cfg.LoRa.LowDatarateOptimize = 0x01;
            }
            else
            {
                sx127x_ptr->cfg.LoRa.LowDatarateOptimize = 0x00;
            }

            if( freqHopOn == true )
            {
            	sx127x_reg_read(spi, REG_LR_PLLHOP, &reg);
                sx127x_reg_write(spi, REG_LR_PLLHOP, (reg&RFLR_PLLHOP_FASTHOP_MASK)|RFLR_PLLHOP_FASTHOP_ON);
                sx127x_reg_write(spi, REG_LR_HOPPERIOD, hopPeriod);
            }

			sx127x_reg_read(spi, REG_LR_MODEMCONFIG1, &reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG1,
                         ( reg &
                           RFLR_MODEMCONFIG1_BW_MASK &
                           RFLR_MODEMCONFIG1_CODINGRATE_MASK &
                           RFLR_MODEMCONFIG1_IMPLICITHEADER_MASK ) |
                           ( bandwidth << 4 ) | ( coderate << 1 ) |
                           fixlen );

			sx127x_reg_read(spi, REG_LR_MODEMCONFIG2, &reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG2,
                           (reg&
                           RFLR_MODEMCONFIG2_SF_MASK &
                           RFLR_MODEMCONFIG2_RXPAYLOADCRC_MASK ) |
                           ( datarate << 4 ) | ( crcOn << 2 ) );

			sx127x_reg_read(spi, REG_LR_MODEMCONFIG3, &reg);
            sx127x_reg_write(spi, REG_LR_MODEMCONFIG3,
                            (reg&
                            RFLR_MODEMCONFIG3_LOWDATARATEOPTIMIZE_MASK ) |
                            (SX1276.Settings.LoRa.LowDatarateOptimize << 3 ) );

            sx127x_reg_write(spi, REG_LR_PREAMBLEMSB, ( preambleLen >> 8 ) & 0x00FF );
            sx127x_reg_write(spi, REG_LR_PREAMBLELSB, preambleLen & 0xFF );

            if( datarate == 6 )
            {
            	sx127x_reg_read(spi, REG_LR_DETECTOPTIMIZE, &reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE,
                             ( reg &
                               RFLR_DETECTIONOPTIMIZE_MASK ) |
                               RFLR_DETECTIONOPTIMIZE_SF6 );
                sx127x_reg_write(spi, REG_LR_DETECTIONTHRESHOLD,
                             RFLR_DETECTIONTHRESH_SF6 );
            }
            else
            {
            	SX1276Read(spi, REG_LR_DETECTOPTIMIZE, &reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE,
                             ( reg &
                             RFLR_DETECTIONOPTIMIZE_MASK ) |
                             RFLR_DETECTIONOPTIMIZE_SF7_TO_SF12 );
                sx127x_reg_write(spi, REG_LR_DETECTIONTHRESHOLD,
                             RFLR_DETECTIONTHRESH_SF7_TO_SF12 );
            }
        }
        break;
    }

	return ret;
}


int sx127x_setrx(struct sx127x *sx127x_ptr)
{
	int ret = 0;
	u8 reg = 0;
    bool rxContinuous = true;
	RadioModems_t modem = sx127x_ptr->cfg.Modem;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);

    switch(modem)
    {
  
    case MODEM_FSK:
        break;
    case MODEM_LORA:
        {
			u32 freq = sx127x_ptr->cfg.LoRa.rChannel;
			u32 bandwidth = sx127x_ptr->cfg.LoRa.rBandwidth;
			bool FreqHopOn = sx127x_ptr->cfg.LoRa.FreqHopOn;
			bool IqInverted = sx127x_ptr->cfg.LoRa.IqInverted;
            if(IqInverted == true)
            {
            	sx127x_reg_read(spi REG_LR_INVERTIQ, &reg);
                sx127x_reg_write(spi, REG_LR_INVERTIQ, ((reg&RFLR_INVERTIQ_TX_MASK&RFLR_INVERTIQ_RX_MASK)|RFLR_INVERTIQ_RX_ON|RFLR_INVERTIQ_TX_OFF));
                sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_ON );
            }
            else
            {
            	sx127x_reg_read(spi, REG_LR_INVERTIQ, &reg);
                sx127x_reg_write(spi, REG_LR_INVERTIQ, ((reg&RFLR_INVERTIQ_TX_MASK&RFLR_INVERTIQ_RX_MASK)|RFLR_INVERTIQ_RX_OFF|RFLR_INVERTIQ_TX_OFF));
                sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_OFF );
            }

            // ERRATA 2.3 - Receiver Spurious Reception of a LoRa Signal
            
            if(bandwidth < 9)
            {
            	sx127x_reg_read(spi, REG_LR_DETECTOPTIMIZE, reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE, (reg & 0x7F));
                sx127x_reg_write(spi, REG_LR_TEST30, 0x00);
                switch(bandwidth)
                {
                case 0: // 7.8 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x48);
                    sx127x_set_freq(sx127x_ptr, (freq + 7810));
                    break;
                case 1: // 10.4 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x44);
                    sx127x_set_freq(sx127x_ptr, (freq + 10420));
                    break;
                case 2: // 15.6 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x44);
                    sx127x_set_freq(sx127x_ptr, (freq + 15620));
                    break;
                case 3: // 20.8 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x44);
                    sx127x_set_freq(sx127x_ptr, (freq + 20830));
                    break;
                case 4: // 31.2 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x44 );
                    sx127x_set_freq(sx127x_ptr, (freq + 31250));
                    break;
                case 5: // 41.4 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x44);
                    sx127x_set_freq(sx127x_ptr, (freq + 41670));
                    break;
                case 6: // 62.5 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x40);
                    break;
                case 7: // 125 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x40);
                    break;
                case 8: // 250 kHz
                    sx127x_reg_write(spi, REG_LR_TEST2F, 0x40);
                    break;
                }
            }
            else
            {
            	sx127x_reg_read(spi, REG_LR_DETECTOPTIMIZE, &reg);
                sx127x_reg_write(spi, REG_LR_DETECTOPTIMIZE, (reg | 0x80));
            }

            rxContinuous = sx127x_ptr->cfg.LoRa.RxContinuous;
			//we just use only this recv mode
			rxContinuous = true;
            if(FreqHopOn == true)
            {
                sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, //RFLR_IRQFLAGS_RXTIMEOUT |
                                                  //RFLR_IRQFLAGS_RXDONE |
                                                  //RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                  RFLR_IRQFLAGS_VALIDHEADER |
                                                  RFLR_IRQFLAGS_TXDONE |
                                                  RFLR_IRQFLAGS_CADDONE |
                                                  //RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                  RFLR_IRQFLAGS_CADDETECTED);

                // DIO0=RxDone, DIO2=FhssChangeChannel
                sx127x_reg_read(spi, REG_DIOMAPPING1, &reg);
                sx127x_reg_write(spi, REG_DIOMAPPING1, (reg&RFLR_DIOMAPPING1_DIO0_MASK&RFLR_DIOMAPPING1_DIO2_MASK) | 
														RFLR_DIOMAPPING1_DIO0_00|RFLR_DIOMAPPING1_DIO2_00);
            }
            else
            {
                sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, //RFLR_IRQFLAGS_RXTIMEOUT |
                                                  //RFLR_IRQFLAGS_RXDONE |
                                                  //RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                  RFLR_IRQFLAGS_VALIDHEADER |
                                                  RFLR_IRQFLAGS_TXDONE |
                                                  RFLR_IRQFLAGS_CADDONE |
                                                  RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                  RFLR_IRQFLAGS_CADDETECTED );

                // DIO0=RxDone
                sx127x_reg_read(spi, REG_DIOMAPPING1, &reg);
                sx127x_reg_write(spi, REG_DIOMAPPING1, (reg&RFLR_DIOMAPPING1_DIO0_MASK)|RFLR_DIOMAPPING1_DIO0_00);
            }
            sx127x_reg_write(spi, REG_LR_FIFORXBASEADDR, 0 );
            sx127x_reg_write(spi, REG_LR_FIFOADDRPTR, 0 );
        }
        break;
    }

    if( SX1276.Settings.Modem == MODEM_FSK )
    {
        sx127x_set_opmode(sx127x_ptr, RF_OPMODE_RECEIVER );
    }
    else
    {
        if( rxContinuous == true )
        {
            sx127x_set_opmode(sx127x_ptr, RFLR_OPMODE_RECEIVER);
        }
        else
        {
            sx127x_set_opmode(sx127x_ptr, RFLR_OPMODE_RECEIVER_SINGLE);
        }
    }

	return ret;
}


void sx127x_settx(struct sx127x *sx127x_ptr, u8 *buffer_ptr, u8 buffer_len)
{
	int ret = 0;
	u8 reg = 0;
    uint32_t txTimeout = 0;
	RadioModems_t modem = sx127x_ptr->cfg.Modem;
	struct spi_device *spi = to_spi_device(sx127x_ptr->dev);

    switch(modem)
    {
    case MODEM_FSK:
        break;
    case MODEM_LORA:
        {
			bool FreqHopOn = sx127x_ptr->cfg.LoRa.FreqHopOn;
			bool IqInverted = sx127x_ptr->cfg.LoRa.IqInverted;
            if(IqInverted == true)
            {
            	sx127x_reg_read(spi, REG_LR_INVERTIQ, &reg);
                sx127x_reg_write(spi, REG_LR_INVERTIQ, ((reg & RFLR_INVERTIQ_TX_MASK & RFLR_INVERTIQ_RX_MASK) |
														RFLR_INVERTIQ_RX_OFF | RFLR_INVERTIQ_TX_ON));
                sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_ON );
            }
            else
            {
            	sx127x_reg_read(spi, REG_LR_INVERTIQ, &reg);
                sx127x_reg_write(spi, REG_LR_INVERTIQ, ((reg & RFLR_INVERTIQ_TX_MASK & RFLR_INVERTIQ_RX_MASK) | 
														RFLR_INVERTIQ_RX_OFF | RFLR_INVERTIQ_TX_OFF));
                sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_OFF );
            }

            // Initializes the payload size
            sx127x_reg_write(spi, REG_LR_PAYLOADLENGTH, buffer_len);

            // Full buffer used for Tx
            sx127x_reg_write(spi, REG_LR_FIFOTXBASEADDR, 0 );
            sx127x_reg_write(spi, REG_LR_FIFOADDRPTR, 0 );

            // FIFO operations can not take place in Sleep mode
            sx127x_reg_read(spi, REG_OPMODE, &reg);
            if((reg & ~RF_OPMODE_MASK) == RF_OPMODE_SLEEP)
            {
                sx127x_set_stby(sx127x_ptr);
                mdelay( 1 );
            }
            // Write payload buffer
            //SX1276WriteFifo( buffer_ptr, buffer_len);

			if(FreqHopOn == true)
            {
                sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                                  RFLR_IRQFLAGS_RXDONE |
                                                  RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                  RFLR_IRQFLAGS_VALIDHEADER |
                                                  //RFLR_IRQFLAGS_TXDONE |
                                                  RFLR_IRQFLAGS_CADDONE |
                                                  //RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                  RFLR_IRQFLAGS_CADDETECTED );

                // DIO0=TxDone, DIO2=FhssChangeChannel
                sx127x_reg_read(spi, REG_DIOMAPPING1, &reg);
                sx127x_reg_write(spi, REG_DIOMAPPING1, (reg & RFLR_DIOMAPPING1_DIO0_MASK & RFLR_DIOMAPPING1_DIO2_MASK) | 
														RFLR_DIOMAPPING1_DIO0_01 | RFLR_DIOMAPPING1_DIO2_00);
            }
            else
            {
                sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                                  RFLR_IRQFLAGS_RXDONE |
                                                  RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                  RFLR_IRQFLAGS_VALIDHEADER |
                                                  //RFLR_IRQFLAGS_TXDONE |
                                                  RFLR_IRQFLAGS_CADDONE |
                                                  RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                  RFLR_IRQFLAGS_CADDETECTED );

                // DIO0=TxDone
				sx127x_reg_read(spi, REG_DIOMAPPING1, &reg);
                sx127x_reg_write(spi, REG_DIOMAPPING1, (reg & RFLR_DIOMAPPING1_DIO0_MASK) | RFLR_DIOMAPPING1_DIO0_01);
            }
        }
        break;
    }


    sx127x_set_opmode(sx127x_ptr, RF_OPMODE_TRANSMITTER);

	return ret;
}


int sx127x_start_rx(struct sx127x *sx127x_ptr)
{
	int ret = 0;

	ret = sx127x_set_rxconfig(sx127x_ptr);
	if(ret < 0)
	{
		goto error;
	}

	ret = sx127x_setrx(sx127x_ptr);
	if(ret < 0)
	{
		goto error;
	}
	
error:

	return ret;
}

int sx127x_start(struct sx127x *sx127x_ptr)
{
	int ret = 0;
	
	ret = sx127x_set_rxconfig(sx127x_ptr);
	if(ret < 0)
	{
		goto error;
	}

	ret = sx127x_setrx(sx127x_ptr);
	if(ret < 0)
	{
		goto error;
	}


	return ret;
}






























int SX127XGetModem(struct sx127x *data, enum sx127x_modulation *modulation)
{
    int ret = 0;
    u8 opmode;
    
    ret = sx127x_reg_read(data->spidevice, REG_OPMODE, &opmode);
    if(ret < 0)
    {
        goto error;
    }
    
    if(opmode & RFLR_OPMODE_LONGRANGEMODE_ON) {
		*modulation = SX127X_MODULATION_LORA;
	}
	else {
		opmode = opmode & SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE;
		if(opmode == SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE_FSK) {
			*modulation = SX127X_MODULATION_FSK;
		}
		else if(opmode == SX127X_REG_OPMODE_FSKOOK_MODULATIONTYPE_OOK) {
			*modulation = SX127X_MODULATION_OOK;
		}else{
            *modulation = SX127X_MODULATION_INVALID;
        }
	}

error:

    return ret;
}
static enum sx127x_modulation sx127x_getmodulation(struct sx127x *data) {
	int ret;
    enum sx127x_modulation modem;
    
    ret = SX127XGetModem(data, &modem);
    if(ret < 0)
    {
       goto error;
    }

    return modem;
    
error:
    
	return SX127X_MODULATION_INVALID;
}

static int sx127x_indexofstring(const char* str, const char** options, unsigned noptions){
	int i;
	for (i = 0; i < noptions; i++) {
		if (sysfs_streq(str, options[i])) {
			return i;
		}
	}
	return -1;
}

static ssize_t sx127x_modulation_show(struct device *child, struct device_attribute *attr, char *buf)
{
	struct sx127x *data = dev_get_drvdata(child);
	u8 opmode;
	enum sx127x_modulation mod;
	int ret;
	mutex_lock(&data->mutex);
	
	mod = sx127x_getmodulation(data);
	if(mod == SX127X_MODULATION_INVALID){
		ret = sprintf(buf, "%s\n", invalid);
	}
	else{
		ret = sprintf(buf, "%s\n", modstr[mod]);
	}
	mutex_unlock(&data->mutex);
	return ret;

}

static int SX127xSetModem(struct sx127x *data, enum sx127x_modulation modulation){
	u8 opmode;
	sx127x_reg_read(data->spidevice, SX127X_REG_OPMODE, &opmode);

	// LoRa mode bit can only be changed in sleep mode
	if(opmode & SX127X_REG_OPMODE_MODE){
		dev_warn(data->chardevice, "switching to sleep mode before changing modulation\n");
		opmode &= ~SX127X_REG_OPMODE_MODE;
		sx127x_reg_write(data->spidevice, SX127X_REG_OPMODE, opmode);
	}

	dev_warn(data->chardevice, "setting modulation to %s\n", modstr[modulation]);
	switch(modulation){
		case SX127X_MODULATION_FSK:
		case SX127X_MODULATION_OOK:
			opmode &= ~SX127X_REG_OPMODE_LONGRANGEMODE;
            data->cfg.modulation = modulation;
			data->loraregmap = 0;
			break;
		case SX127X_MODULATION_LORA:
			opmode |= SX127X_REG_OPMODE_LONGRANGEMODE;
			data->loraregmap = 1;
			break;
        default:
            break;
	}
	sx127x_reg_write(data->spidevice, SX127X_REG_OPMODE, opmode);
	return 0;
}

static int sx127x_setmodulation(struct sx127x *data, enum sx127x_modulation modulation){
    int ret = 0;

	dev_warn(data->chardevice, "setting modulation to %s\n", modstr[modulation]);
	switch(modulation){
		case SX127X_MODULATION_FSK:
		case SX127X_MODULATION_OOK:
			data->loraregmap = 0;
            data->cfg.modulation = modulation;
            ret = SX127xSetModem(data, modulation);
            if(ret < 0)
            {
                goto error;
            }
			break;
		case SX127X_MODULATION_LORA:
			data->loraregmap = 1;
            data->cfg.modulation = modulation;
            ret = SX127xSetModem(data, modulation);
            if(ret < 0)
            {
                goto error;
            }
			break;
        default:
            break;
	}

error:

    return ret;
}


static ssize_t sx127x_modulation_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	struct sx127x *data = dev_get_drvdata(dev);
	int idx = sx127x_indexofstring(buf, modstr, ARRAY_SIZE(modstr));
	if(idx == -1){
		dev_warn(dev, "invalid modulation type\n");
		goto out;
	}
	mutex_lock(&data->mutex);
	sx127x_setmodulation(data, idx);
	mutex_unlock(&data->mutex);
out:
	return count;
}

static DEVICE_ATTR(modulation, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_modulation_show, sx127x_modulation_store);

int SX127XGetOpmode(struct sx127x *data, enum sx127x_opmode *mode)
{
    int ret = 0;
    u8 opmode = 0;
    
    mutex_lock(&data->mutex);
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_OPMODE, &opmode);
    if(ret < 0)
    {
        goto error;
    }
	opmode = opmode & SX127X_REG_OPMODE_MODE;

    switch(opmode)
    {
    case SX127X_OPMODE_SLEEP:
        *mode = SX127X_OPMODE_SLEEP;
        break;
    case SX127X_OPMODE_STANDBY:
        *mode = SX127X_OPMODE_STANDBY;
        break;
    case SX127X_OPMODE_FSTX:
        *mode = SX127X_OPMODE_FSTX;
        break;
    case SX127X_OPMODE_TX:
        *mode = SX127X_OPMODE_TX;
        break;
    case SX127X_OPMODE_FSRX:
        *mode = SX127X_OPMODE_FSRX;
        break;
    case SX127X_OPMODE_RX:
        *mode = SX127X_OPMODE_RX;
        break;
    case SX127X_OPMODE_RXCONTINUOS:
        *mode = SX127X_OPMODE_RXCONTINUOS;
        break;
    case SX127X_OPMODE_RXSINGLE:
        *mode = SX127X_OPMODE_RXSINGLE;
        break;
    case SX127X_OPMODE_CAD:
        *mode = SX127X_OPMODE_CAD;
        break;
    default:
        break;
    }
    
	mutex_unlock(&data->mutex);

error:

    return ret;
}

static ssize_t sx127x_opmode_show(struct device *child, struct device_attribute *attr, char *buf)
{
    int ret = 0;
	struct sx127x *data = dev_get_drvdata(child);
	u8 opmode;
    enum sx127x_opmode mode;
	

    ret = SX127XGetOpmode(data, &mode);
    if(ret < 0)
    {
        goto error;
    }
    
	if(mode > 4){
		ret = sprintf(buf, "%s\n", opmodestr[mode + 1]);
	}
	else {
		ret =sprintf(buf, "%s\n", opmodestr[mode]);
	}

error:
    
	return ret;
}

static int sx127x_toggletxrxen(struct sx127x *data, bool tx){
	if(data->gpio_txen){
		if(tx){
			dev_warn(data->chardevice, "enabling tx\n");
		}
		gpiod_set_value(data->gpio_txen, tx);
	}
	if(data->gpio_rxen){
		if(!tx){
			dev_warn(data->chardevice, "enabling rx\n");
		}
		gpiod_set_value(data->gpio_rxen, !tx);
	}
	return 0;
}

int SX127XSetOpmode(struct sx127x *data, enum sx127x_opmode mode)
{
    int ret = 0;
    u8 opmode, diomapping1;

    ret = sx127x_reg_read(data->spidevice, SX127X_REG_OPMODE, &opmode);
    if(mode < SX127X_OPMODE_SLEEP || mode > SX127X_OPMODE_CAD){
        ret = -EINVAL;
        dev_err(data->chardevice, "invalid opmode\n");
    }
    else if((opmode & SX127X_REG_OPMODE_LONGRANGEMODE) && (mode == SX127X_OPMODE_RX)){
        dev_err(data->chardevice, "opmode %s not valid in LoRa mode\n", opmodestr[mode]);
    }
    else if(!(opmode & SX127X_REG_OPMODE_LONGRANGEMODE) && (mode > SX127X_OPMODE_RX)) {
        dev_err(data->chardevice, "opmode %s not valid in FSK/OOK mode\n", opmodestr[mode]);
    }
    else {
        
        dev_warn(data->chardevice, "setting opmode to %s\n", opmodestr[mode]);
        sx127x_reg_read(data->spidevice, SX127X_REG_DIOMAPPING1, &diomapping1);
        diomapping1 &= ~SX127X_REG_DIOMAPPING1_DIO0;
        switch(mode){
        case SX127X_OPMODE_CAD:
            diomapping1 |= SX127X_REG_DIOMAPPING1_DIO0_CADDONE;
            sx127x_toggletxrxen(data, false);
            break;
        case SX127X_OPMODE_TX:
            diomapping1 |= SX127X_REG_DIOMAPPING1_DIO0_TXDONE;
            sx127x_toggletxrxen(data, true);
            break;
        case SX127X_OPMODE_RX:
        case SX127X_OPMODE_RXCONTINUOS:
        case SX127X_OPMODE_RXSINGLE:
            diomapping1 |= SX127X_REG_DIOMAPPING1_DIO0_RXDONE;
            sx127x_toggletxrxen(data, false);
            break;
        default:
            dev_warn(data->chardevice, "disabling rx and tx\n");
            gpiod_set_value(data->gpio_rxen, 0);
            gpiod_set_value(data->gpio_txen, 0);
            break;
        }
        opmode &= ~SX127X_REG_OPMODE_MODE;
        if(mode > SX127X_OPMODE_RX){
            mode -= 1;
        }
        opmode |= mode;
        sx127x_reg_write(data->spidevice, SX127X_REG_DIOMAPPING1, diomapping1);
        sx127x_reg_write(data->spidevice, SX127X_REG_OPMODE, opmode);
    }
    return ret;

}

static int sx127x_setopmode(struct sx127x *data, enum sx127x_opmode mode, bool retain){
    int ret = 0;

    ret = SX127XSetOpmode(data, mode);
    if(ret < 0)
    {
        goto error;
    }
    
    if(retain){
	    data->opmode = mode;
	}

error:
    
	return ret;
}

int SX127XSetSyncWord(struct sx127x *data, u8 syncword)
{
    int ret = 0;
    
    ret = sx127x_reg_write(data->spidevice, SX127X_REG_LORA_SYNCWORD, syncword);

    return ret;
}

static int sx127x_setsyncword(struct sx127x *data, u8 syncword){
    int ret = 0;
    
    dev_warn(data->chardevice, "setting syncword to %d\n", syncword);
	ret = SX127XSetSyncWord(data, syncword);
    if(ret < 0)
    {
        goto error;
    }
    data->cfg.syncword = syncword;
    
error:
    
	return ret;
}

int SX127XSetInvertIQ(struct sx127x *data, bool invert)
{
    int ret = 0;
    u8 reg;
    
    ret = sx127x_reg_read(data->spidevice, SX127X_REG_LORA_INVERTIQ, &reg);
    if(ret < 0)
    {
        goto error;
    }
    
	if(invert)
		reg |= SX127X_REG_LORA_INVERTIQ_INVERTIQ;
	else
		reg &= ~SX127X_REG_LORA_INVERTIQ_INVERTIQ;
	ret = sx127x_reg_write(data->spidevice, SX127X_REG_LORA_INVERTIQ, reg);
    if(ret < 0)
    {
        goto error;
    }

error:
    
    return ret;
}

static int sx127x_setinvertiq(struct sx127x *data, bool invert){
    int ret = 0;
    
	dev_warn(data->chardevice, "setting invertiq to %d\n", invert);
    ret = SX127XSetInvertIQ(data, invert);
    if(ret < 0)
    {
        goto error;
    }
    data->cfg.invertiq = invert;
error:
    
	return ret;
}

int SX127XSetCrc(struct sx127x *data, bool crc)
{
    int ret = 0;
    u8 reg;

    ret = sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG2, &reg);
    if(ret < 0)
    {
        goto error;
    }
    
	if(crc)
		reg |= SX127X_REG_LORA_MODEMCONFIG2_RXPAYLOADCRCON;
	else
		reg &= ~SX127X_REG_LORA_MODEMCONFIG2_RXPAYLOADCRCON;
	ret = sx127x_reg_write(data->spidevice, SX127X_REG_LORA_MODEMCONFIG2, reg);
    if(ret < 0)
    {
        goto error;
    }

error:

    return ret;
}

static int sx127x_setcrc(struct sx127x *data, bool crc){
	int ret = 0;
    
	dev_warn(data->chardevice, "setting crc to %d\n", crc);

    ret = SX127XSetCrc(data, crc);
    if(ret < 0)
    {
        goto error;
    }
    data->cfg.crc = crc;
error:
    
	return ret;
}

static ssize_t sx127x_opmode_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	struct sx127x *data = dev_get_drvdata(dev);
	int idx;
	enum sx127x_opmode mode;

	idx = sx127x_indexofstring(buf, opmodestr, ARRAY_SIZE(opmodestr));
	if(idx == -1){
		dev_err(dev, "invalid opmode\n");
		goto out;
	}
	mutex_lock(&data->mutex);
	mode = idx;
	sx127x_setopmode(data, mode, true);
	mutex_unlock(&data->mutex);
out:
	return count;
}

static DEVICE_ATTR(opmode, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_opmode_show, sx127x_opmode_store);

int SX127XGetFreq(struct sx127x *data, u32 *freq)
{
    int ret = 0;
    u8 msb, mld, lsb;
	u32 frf;
	

    mutex_lock(&data->mutex);
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_FRFMSB, &msb);
    if(ret < 0)
    {
        goto error;
    }
    
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_FRFMLD, &mld);
    if(ret < 0)
    {
        goto error;
    }
    
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_FRFLSB, &lsb);
    if(ret < 0)
    {
        goto error;
    }
    
	frf = (msb << 16) | (mld << 8) | lsb;
	freq = ((u64)data->fosc * frf) / 524288;
	mutex_unlock(&data->mutex);

error:

    return ret;
}

static ssize_t sx127x_carrierfrequency_show(struct device *dev, struct device_attribute *attr, char *buf)
{
    int ret = 0;
    u32 freq = 0;
	struct sx127x *data = dev_get_drvdata(dev);

    ret = SX127XGetFreq(data, &freq);
	if(ret < 0)
    {
        goto error;
    }
    return sprintf(buf, "%u\n", freq);

error:

    return ret;
}

int Sx127XSetFreq(struct sx127x *data, u32 freq)
{
    int ret = 0;
    u8 opmode, newopmode;
    u64 freq_temp = 0;
    u32 reg = 0;
    
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_OPMODE, &opmode);
    if(ret < 0)
    {
        goto error;
    }
    
	newopmode = opmode & ~SX127X_REG_OPMODE_LOWFREQUENCYMODEON;
	if(freq < 700000000){
		newopmode |= SX127X_REG_OPMODE_LOWFREQUENCYMODEON;
	}
	if(newopmode != opmode){
		dev_warn(data->chardevice, "toggling LF/HF bit\n");
		ret = sx127x_reg_write(data->spidevice, SX127X_REG_OPMODE, newopmode);
        if(ret < 0)
        {
            goto error;
        }
	}

	
	freq_temp = freq * 524288;

	do_div(freq_temp, data->fosc);
    reg = (u32)freq_temp;
	ret = sx127x_reg_write24(data->spidevice, SX127X_REG_FRFMSB, reg);
    if(ret < 0)
    {
        goto error;
    }
    
error:
    
	return ret;
}
    
static int sx127x_setcarrierfrequency(struct sx127x *data, u32 freq){
    int ret = 0;

    dev_warn(data->chardevice, "setting carrier frequency to %llu\n", freq);

    ret = Sx127XSetFreq(data, freq);
    if(ret < 0)
    {
        goto error;
    }
    data->cfg.freq = freq;
error:

    return ret;
}

static ssize_t sx127x_carrierfrequency_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	struct sx127x *data = dev_get_drvdata(dev);
	u32 freq;

	if(kstrtou32(buf, 10, &freq)){
		goto out;
	}
	mutex_lock(&data->mutex);
	sx127x_setcarrierfrequency(data, freq);
	mutex_unlock(&data->mutex);
	out:
	return count;
}

static DEVICE_ATTR(carrierfrequency, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_carrierfrequency_show, sx127x_carrierfrequency_store);

static ssize_t sx127x_rssi_show(struct device *child, struct device_attribute *attr, char *buf)
{
    return sprintf(buf, "%d\n", 0);
}

static DEVICE_ATTR(rssi, S_IRUSR | S_IRGRP | S_IROTH, sx127x_rssi_show, NULL);

int SX127XGetSF(struct sx127x *data, int *sf)
{
    int ret= 0;
    u8 config2;
    
    sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG2, &config2);
	*sf = config2 >> SX127X_REG_LORA_MODEMCONFIG2_SPREADINGFACTOR_SHIFT;
}

static ssize_t sx127x_sf_show(struct device *dev, struct device_attribute *attr, char *buf)
{
	struct sx127x *data = dev_get_drvdata(dev);
	int sf = 0;
	
	mutex_lock(&data->mutex);
	SX127XGetSF(data, &sf);
	mutex_unlock(&data->mutex);
    return sprintf(buf, "%d\n", sf);
}

int SX127XSetSF(struct sx127x *data, unsigned sf)
{
    int ret = 0;
	u8 r;
	
	// set the spreading factor
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG2, &r);
	r &= ~SX127X_REG_LORA_MODEMCONFIG2_SPREADINGFACTOR;
	r |= sf << SX127X_REG_LORA_MODEMCONFIG2_SPREADINGFACTOR_SHIFT;
	sx127x_reg_write(data->spidevice, SX127X_REG_LORA_MODEMCONFIG2, r);

	// set the detection optimization magic number depending on the spreading factor
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_DETECTOPTIMIZATION, &r);
	r &= ~SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE;
	if(sf == 6){
		r |= SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE_SF6;
	}
	else{
		r |= SX127X_REG_LORA_DETECTOPTIMIZATION_DETECTIONOPTIMIZE_SF7SF12;
	}
	sx127x_reg_write(data->spidevice, SX127X_REG_LORA_DETECTOPTIMIZATION, r);

	// set the low data rate bit
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG3, &r);
	r |= SX127X_REG_LORA_MODEMCONFIG3_LOWDATARATEOPTIMIZE;
	sx127x_reg_write(data->spidevice, SX127X_REG_LORA_MODEMCONFIG3, r);
    
	return ret;

}

static int sx127x_setsf(struct sx127x *data, unsigned sf){
    int ret = 0;
    
    dev_info(data->chardevice, "setting spreading factor to %u\n", sf);
    ret = SX127XSetSF(data, sf);
    if(ret < 0)
    {
        goto error;
    }
    data->cfg.sf = sf;
error:
    
    return ret;
}

static ssize_t sx127x_sf_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	struct sx127x *data = dev_get_drvdata(dev);
	int sf;
	if(kstrtoint(buf, 10, &sf)){
		goto out;
	}
	mutex_lock(&data->mutex);
	sx127x_setsf(data, sf);
	mutex_unlock(&data->mutex);
	out:
	return count;
}

static DEVICE_ATTR(sf, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_sf_show, sx127x_sf_store);

int SX127XGetBW(struct sx127x *data, unsigned *bandwidth)
{
    int ret =0;
    u8 config1;
	int bw;
    
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG1, &config1);
	bw = config1 >> SX127X_REG_LORA_MODEMCONFIG1_BW_SHIFT;
	
    
    return ret;
}

static ssize_t sx127x_bw_show(struct device *dev, struct device_attribute *attr, char *buf)
{
    int ret = 0;
    int bandwidth = 0;
	struct sx127x *data = dev_get_drvdata(dev);


	mutex_lock(&data->mutex);
    ret = SX127XGetBW(data, &bandwidth);
    if(bandwidth > SX127X_REG_LORA_MODEMCONFIG1_BW_MAX){
        ret = sprintf(buf, "invalid\n");
    }
    else {
        ret = sprintf(buf, "%d\n", bwmap[bandwidth]);
    }

	mutex_unlock(&data->mutex);
	return ret;
}

static ssize_t sx127x_bw_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	//struct sx127x *data = dev_get_drvdata(dev);
	return count;
}

static DEVICE_ATTR(bw, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_bw_show, sx127x_bw_store);

static char* crmap[] = { NULL, "4/5", "4/6", "4/7", "4/8" };

int SX127XGetCodingRate(struct sx127x *data, unsigned *codingrate)
{
    int ret = 0;
    u8 config1;

    ret = sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG1, &config1);
	*codingrate = (config1 & SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE) >> SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_SHIFT;

    return ret;
}

static ssize_t sx127x_codingrate_show(struct device *dev, struct device_attribute *attr, char *buf)
{
	struct sx127x *data = dev_get_drvdata(dev);
	
	int cr, ret;

	mutex_lock(&data->mutex);
	ret = SX127XGetCodingRate(data, &cr);
	if(cr < SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_MIN ||
			cr > SX127X_REG_LORA_MODEMCONFIG1_CODINGRATE_MAX){
		ret = sprintf(buf, "invalid\n");
	}
	else {
		ret = sprintf(buf, "%s\n", crmap[cr]);
	}
	mutex_unlock(&data->mutex);
    return ret;
}

int SX127XSetCodingRate(struct sx127x *data, unsigned codingrate)
{
    int ret = 0;

error:

    return ret;
}

static ssize_t sx127x_codingrate_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	//struct sx127x *data = dev_get_drvdata(dev);
	return count;
}

static DEVICE_ATTR(codingrate, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_codingrate_show, sx127x_codingrate_store);

int SX127XGetImplicitHeader(struct sx127x *data, unsigned *implicitheader)
{
    int ret = 0;
    u8 config1;

    ret = sx127x_reg_read(data->spidevice, SX127X_REG_LORA_MODEMCONFIG1, &config1);
	*implicitheader = config1 & SX127X_REG_LORA_MODEMCONFIG1_IMPLICITHEADERMODEON;

    return ret;
}

static ssize_t sx127x_implicitheadermodeon_show(struct device *dev, struct device_attribute *attr, char *buf)
{
    int ret = 0;
	struct sx127x *data = dev_get_drvdata(dev);
	
	int hdrmodeon;

	mutex_lock(&data->mutex);
    ret = SX127XGetImplicitHeader(data, &hdrmodeon);
	mutex_unlock(&data->mutex);
    return sprintf(buf, "%d\n", hdrmodeon);
}

int SX127XSetImplicitHeader(struct sx127x *data, unsigned *implicitheader)
{
    int ret = 0;

    return ret;
}
static ssize_t sx127x_implicitheadermodeon_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	//struct sx127x *data = dev_get_drvdata(dev);
	return count;
}

static DEVICE_ATTR(implicitheadermodeon, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_implicitheadermodeon_show, sx127x_implicitheadermodeon_store);

int SX127XGetPaoutput(struct sx127x *data, unsigned *idx)
{
    int ret = 0;
    u8 paconfig;

    sx127x_reg_read(data->spidevice, SX127X_REG_PACONFIG, &paconfig);
	*idx = (paconfig & SX127X_REG_PACONFIG_PASELECT) ? 1 : 0;

    return ret;
}

static ssize_t sx127x_paoutput_show(struct device *dev, struct device_attribute *attr, char *buf)
{
    int ret = 0;
    int idx;
	struct sx127x *data = dev_get_drvdata(dev);

	mutex_lock(&data->mutex);
	ret = SX127XGetPaoutput(data, &idx);
	mutex_unlock(&data->mutex);
    return sprintf(buf, "%s\n", paoutput[idx]);
}

static int SX127XSetPaoutput(struct sx127x *data, enum sx127x_pa pa){
	int ret = 0;
	u8 paconfig;
    
	sx127x_reg_read(data->spidevice, SX127X_REG_PACONFIG, &paconfig);
	switch(pa){
		case SX127X_PA_RFO:
			paconfig &= ~SX127X_REG_PACONFIG_PASELECT;
			break;
		case SX127X_PA_PABOOST:
			paconfig |= SX127X_REG_PACONFIG_PASELECT;
			break;
	}
	sx127x_reg_write(data->spidevice, SX127X_REG_PACONFIG, paconfig);
    
	return ret;
}

static int sx127x_setpaoutput(struct sx127x *data, enum sx127x_pa pa){
	int ret = 0;

    ret = SX127XSetPaoutput(data, pa);
	switch(pa){
		case SX127X_PA_RFO:
			data->cfg.pa = SX127X_PA_RFO;
			break;
		case SX127X_PA_PABOOST:
			data->cfg.pa = SX127X_PA_PABOOST;
			break;
	}
    
	return ret;
}


static ssize_t sx127x_paoutput_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
	//TODO this needs to take into account non-default values for the "padac".
	struct sx127x *data = dev_get_drvdata(dev);
	int idx = sx127x_indexofstring(buf, paoutput, ARRAY_SIZE(paoutput));
	if(idx == -1)
		goto out;
	mutex_lock(&data->mutex);
	sx127x_setpaoutput(data, idx);
	mutex_unlock(&data->mutex);
out:
	return count;
}

static DEVICE_ATTR(paoutput, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH, sx127x_paoutput_show, sx127x_paoutput_store);

int SX127XGetOutputPower(struct sx127x *data, int *outputpower)
{
    int ret = 0;
    u8 paconfig;
    int maxoutputpower = 17;
	

    sx127x_reg_read(data->spidevice, SX127X_REG_PACONFIG, &paconfig);
	if(!(paconfig & SX127X_REG_PACONFIG_PASELECT)){
		maxoutputpower = ((paconfig & SX127X_REG_PACONFIG_MAXPOWER) >> SX127X_REG_PACONFIG_MAXPOWER_SHIFT);
	}
	*outputpower = maxoutputpower - (15 - (paconfig & SX127X_REG_PACONFIG_OUTPUTPOWER));

    return ret;
}

static ssize_t sx127x_outputpower_show(struct device *dev, struct device_attribute *attr, char *buf)
{
    int ret = 0;
	struct sx127x *data = dev_get_drvdata(dev);
	int outputpower;

	mutex_lock(&data->mutex);
	SX127XGetOutputPower(data, &outputpower);
	mutex_unlock(&data->mutex);
    return sprintf(buf, "%d\n", outputpower);
}

int SX127XSetOutputPower(struct sx127x *data, int outputpower)
{
    int ret = 0;

    u8 paconfig;
	ret = sx127x_reg_read(data->spidevice, SX127X_REG_PACONFIG, &paconfig);
	ret = sx127x_reg_write(data->spidevice, SX127X_REG_PACONFIG, paconfig);

    return ret;
}

static ssize_t sx127x_outputpower_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count){
    int ret = 0;
	struct sx127x *data = dev_get_drvdata(dev);
	//int idx = sx127x_indexofstring(buf, paoutput, ARRAY_SIZE(paoutput));
	ret = SX127XSetOutputPower(data, 0);
	return count;
}

static DEVICE_ATTR(outputpower, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH,
		sx127x_outputpower_show, sx127x_outputpower_store);


static irqreturn_t sx127x_top_irq_handler(int irq, void *dev_id)
{
	//struct sx127x *data = dev_id;
    disable_irq_nosync(irq);
	//schedule_work(&data->irq_work);
	return IRQ_HANDLED;
}

static irqreturn_t sx127x_bottem_irq_thread(int irq, void *dev_id)
{
	//struct sx127x *data = container_of(work, struct sx127x, irq_work);
	struct sx127x *data = dev_id;
	u8 irqflags, buf[128], len, snr, rssi;
	u32 fei;
	struct sx127x_pkt pkt;
	mutex_lock(&data->mutex);
	sx127x_reg_read(data->spidevice, SX127X_REG_LORA_IRQFLAGS, &irqflags);
	if(irqflags & SX127X_REG_LORA_IRQFLAGS_RXDONE){
		dev_warn(data->chardevice, "reading packet\n");
		memset(&pkt, 0, sizeof(pkt));

		sx127x_fifo_readpkt(data->spidevice, buf, &len);
		sx127x_reg_read(data->spidevice, SX127X_REG_LORA_PKTSNRVALUE, &snr);
        if( SX1276.Settings.LoRaPacketHandler.SnrValue & 0x80 ) // The SNR sign bit is 1
        {
            // Invert and divide by 4
            snr = ( ( ~SX1276.Settings.LoRaPacketHandler.SnrValue + 1 ) & 0xFF ) >> 2;
            snr = -snr;
        }
        else
        {
            // Divide by 4
            snr = ( SX1276.Settings.LoRaPacketHandler.SnrValue & 0xFF ) >> 2;
        }
		sx127x_reg_read(data->spidevice, SX127X_REG_LORA_PKTRSSIVALUE, &rssi);
		sx127x_reg_read24(data->spidevice, SX127X_REG_LORA_FEIMSB, &fei);
		if( snr < 0 )
        {
            if( SX1276.Settings.Channel > RF_MID_BAND_THRESH )
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_HF + rssi + ( rssi >> 4 ) +
                                                              snr;
            }
            else
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_LF + rssi + ( rssi >> 4 ) +
                                                              snr;
            }
        }
        else
        {
            if( SX1276.Settings.Channel > RF_MID_BAND_THRESH )
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_HF + rssi + ( rssi >> 4 );
            }
            else
            {
                SX1276.Settings.LoRaPacketHandler.RssiValue = RSSI_OFFSET_LF + rssi + ( rssi >> 4 );
            }
        }
		pkt.hdrlen = sizeof(pkt);
		pkt.payloadlen = len;
		pkt.len = pkt.hdrlen + pkt.payloadlen;
		pkt.snr = (__s16)(snr << 2) / 4 ;
		pkt.rssi = -157 + rssi; //TODO fix this for the LF port

		if(irqflags & SX127X_REG_LORA_IRQFLAGS_PAYLOADCRCERROR){
			dev_warn(data->chardevice, "CRC Error for received payload\n");
			pkt.crcfail = 1;
		}

		kfifo_in(&data->out, &pkt, sizeof(pkt));
		kfifo_in(&data->out, buf, len);
		wake_up(&data->readwq);
	}
	else if(irqflags & SX127X_REG_LORA_IRQFLAGS_TXDONE){
		if(data->gpio_txen){
			gpiod_set_value(data->gpio_txen, 0);
		}
		dev_warn(data->chardevice, "transmitted packet\n");
		/* after tx the chip goes back to standby so restore the user selected mode if it wasn't standby */
		if(data->opmode != SX127X_OPMODE_STANDBY){
			dev_info(data->chardevice, "restoring opmode\n");
			sx127x_setopmode(data, data->opmode, false);
		}
		data->transmitted = 1;
		wake_up(&data->writewq);
	}
	else if(irqflags & SX127X_REG_LORA_IRQFLAGS_CADDONE){
		if(irqflags & SX127X_REG_LORA_IRQFLAGS_CADDETECTED){
			dev_info(data->chardevice, "CAD done, detected activity\n");
		}
		else {
			dev_info(data->chardevice, "CAD done, nothing detected\n");
		}
	}
	else {
		dev_err(&data->spidevice->dev, "unhandled interrupt state %02x\n", (unsigned) irqflags);
	}
	sx127x_reg_write(data->spidevice, SX127X_REG_LORA_IRQFLAGS, 0xff);
	mutex_unlock(&data->mutex);
    enable_irq(irq);

    return IRQ_HANDLED;
}


static int drv_open(struct inode *inode, struct file *file)
{
	struct sx127x *data;
	int status = -ENXIO;
    int irq;
	mutex_lock(&device_list_lock);

	list_for_each_entry(data, &device_list, device_entry) {
		if (data->devt == inode->i_rdev) {
			status = 0;
			break;
		}
	}

	if(status){
		pr_debug("sx127x: nothing for minor %d\n", iminor(inode));
		goto err_notfound;
	}

	mutex_lock(&data->mutex);
	if(data->open){
		pr_debug("sx127x: already open\n");
		status = -EBUSY;
		goto err_open;
	}
	data->open = 1;
    irq = gpiod_to_irq(data->gpio_dio0);
    if (!irq) {
		dev_err(&data->spidevice->dev, "No irq in platform data\n");
		status = -EINVAL;
		goto err_open;
	}
    
    status = devm_request_threaded_irq(&data->spidevice->dev, irq, sx127x_top_irq_handler, sx127x_bottem_irq_thread, IRQF_TRIGGER_RISING, DRV_NAME, data);
    if(status < 0)
    {
        goto err_open;
    }
	mutex_unlock(&data->mutex);

	ret = sx127x_init(data);
	
	mutex_unlock(&device_list_lock);

	file->private_data = data;
	return 0;

err_open:
	mutex_unlock(&data->mutex);
err_notfound:
	mutex_unlock(&device_list_lock);
	return status;
}

static ssize_t drv_read(struct file *filp, char __user *buf, size_t count, loff_t *f_pos)
{
	struct sx127x *data = filp->private_data;
	unsigned copied;
	ssize_t ret = 0;
	wait_event_interruptible(data->readwq, kfifo_len(&data->out));
	ret = kfifo_to_user(&data->out, buf, count, &copied);
	if(!ret && copied > 0){
		ret = copied;
	}
	return ret;
}

static ssize_t drv_write(struct file *filp, const char __user *buf, size_t count, loff_t *f_pos)
{
    int ret = 0;
	u8 reg = 0;
	struct spi_device *spi = to_spi_device(stat->dev);
	struct sx127x *data = filp->private_data;
	size_t packetsz, offset, maxpkt = 256;
	u8 kbuf[256];
	dev_info(&data->spidevice->dev, "char device write; %d\n", count);

	sx127x_set_txconfig();
	for(offset = 0; offset < count; offset += maxpkt){
		packetsz = min((count - offset), maxpkt);
		mutex_lock(&data->mutex);
		ret = copy_from_user(kbuf, buf + offset, packetsz);
        if(ret < 0)
        {
            goto error;
        }

		if( SX1276.Settings.LoRa.IqInverted == true )
        {
        	sx127x_reg_read(spi, REG_LR_INVERTIQ, &reg) ;
            sx127x_reg_write(spi, REG_LR_INVERTIQ, ( ( reg& RFLR_INVERTIQ_TX_MASK & RFLR_INVERTIQ_RX_MASK ) | RFLR_INVERTIQ_RX_OFF | RFLR_INVERTIQ_TX_ON ) );
            sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_ON );
        }
        else
        {
        	sx127x_reg_read(spi, REG_LR_INVERTIQ, &reg);
            sx127x_reg_write(spi, REG_LR_INVERTIQ, ( ( reg & RFLR_INVERTIQ_TX_MASK & RFLR_INVERTIQ_RX_MASK ) | RFLR_INVERTIQ_RX_OFF | RFLR_INVERTIQ_TX_OFF ) );
            sx127x_reg_write(spi, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_OFF );
        }
		
		sx127x_setopmode(data, SX127X_OPMODE_STANDBY, false);
		
		sx127x_fifo_writepkt(data->spidevice, kbuf, packetsz);

		if( SX1276.Settings.LoRa.FreqHopOn == true )
        {
            sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                              RFLR_IRQFLAGS_RXDONE |
                                              RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                              RFLR_IRQFLAGS_VALIDHEADER |
                                              //RFLR_IRQFLAGS_TXDONE |
                                              RFLR_IRQFLAGS_CADDONE |
                                              //RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                              RFLR_IRQFLAGS_CADDETECTED );

            // DIO0=TxDone, DIO2=FhssChangeChannel
            SX1276Read(spi, REG_DIOMAPPING1, &reg);
            sx127x_reg_write(spi, REG_DIOMAPPING1, (reg & RFLR_DIOMAPPING1_DIO0_MASK & RFLR_DIOMAPPING1_DIO2_MASK ) | RFLR_DIOMAPPING1_DIO0_01 | RFLR_DIOMAPPING1_DIO2_00 );
        }
        else
        {
            sx127x_reg_write(spi, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                              RFLR_IRQFLAGS_RXDONE |
                                              RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                              RFLR_IRQFLAGS_VALIDHEADER |
                                              //RFLR_IRQFLAGS_TXDONE |
                                              RFLR_IRQFLAGS_CADDONE |
                                              RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                              RFLR_IRQFLAGS_CADDETECTED );

            // DIO0=TxDone
            sx127x_reg_write(spi, REG_DIOMAPPING1, ( SX1276Read( REG_DIOMAPPING1 ) & RFLR_DIOMAPPING1_DIO0_MASK ) | RFLR_DIOMAPPING1_DIO0_01 );
        }
		data->transmitted = 0;
		sx127x_setopmode(data, SX127X_OPMODE_TX, false);
		mutex_unlock(&data->mutex);
		wait_event_interruptible_timeout(data->writewq, data->transmitted, 60 * HZ);
	}

	//rx begin
	mutex_lock(&data->mutex);
	sx127x_start();
	mutex_unlock(&data->mutex);

	return count;

 error:

    return ret;
}

static int drv_release(struct inode *inode, struct file *filp)
{
	struct sx127x *data = filp->private_data;
	mutex_lock(&data->mutex);
	sx127x_setopmode(data, SX127X_OPMODE_STANDBY, true);
	data->open = 0;
	kfifo_reset(&data->out);
	mutex_unlock(&data->mutex);
	return 0;
}

static long drv_ioctl(struct file *filp, unsigned int cmd, unsigned long arg)
{
	struct sx127x *data = filp->private_data;
	int ret = 0;
	
	mutex_lock(&data->mutex);
	switch(cmd){
		case LORA_IOC_RD_MODEM:
		{
			break;
		}
		case LORA_IOC_WR_MODEM:
		{
			u32 val = (u32)arg;		
			switch(val)
			{
			case MODEM_FSK:
				ret = sx127x_set_modem(data, MODEM_FSK);
				data->cfg.Modem = MODEM_FSK;
				break;
			case MODEM_LORA:
				ret = sx127x_set_modem(data, MODEM_FSK);
				data->cfg.Modem = MODEM_FSK;
				break;
			}
			ret = 0;
			break;
		}
		case LORA_IOC_RD_TXFRE:
		{			
			break;
		}
		case LORA_IOC_WR_TXFRE:
		{
			u32 freq = (u32)arg;
			data->cfg.LoRa.tChannel = freq;
			break;
		}
		case LORA_IOC_RD_RXFRE:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_WR_RXFRE:
		{
			u32 freq = (u32)arg;
			data->cfg.LoRa.rChannel = freq;
			break;
		}
		case LORA_IOC_RD_TXBW:
		{
			break;
		}
		case LORA_IOC_WR_TXBW:
		{
			u32 bandwidth = (u32)arg;
			//When using LoRa modem only bandwidths 125, 250 and 500 kHz are supported
			if((bandwidth <= 9) && (bandwidth >= 7))
			{
				data->cfg.LoRa.tBandwidth = bandwidth;	
			}
			
			break;
		}
		case LORA_IOC_RD_RXBW:
		{
			break;
		}
		case LORA_IOC_WR_RXBW:
		{
			u32 bandwidth = (u32)arg;
			data->cfg.LoRa.rBandwidth = bandwidth;
			break;
		}
		case LORA_IOC_RD_TXSF:
		{
			
			break;
		}
		case LORA_IOC_WR_TXSF:
		{
			u32 sf = (u32)arg;
			if((sf <= 12) && (sf >= 6))
			{
				data->cfg.LoRa.tDatarate = sf;
			}
			
			break;
		}
		case LORA_IOC_RD_RXSF:
		{
			
			break;
		}
		case LORA_IOC_WR_RXSF:
		{
			u32 sf = (u32)arg;
			data->cfg.LoRa.rDatarate = sf;
			break;
		}
		case LORA_IOC_RD_TXCR:
		{
			break;
			
		}
		case LORA_IOC_WR_TXCR:
		{
			u8 codingrate = (u8)arg;
			data->cfg.LoRa.tCoderate = codingrate;
			break;	
		}
		case LORA_IOC_RD_RXCR:
		{
			break;
			
		}
		case LORA_IOC_WR_RXCR:
		{
			u8 codingrate = (u8)arg;
			data->cfg.LoRa.rCoderate = codingrate;
			break;	
		}
		case LORA_IOC_RD_POWER:
		{
			break;
		}
		case LORA_IOC_WR_POWER:
		{
			s8 power= (s8)arg;
			data->cfg.LoRa.Power = power;
			break;
		}
		case LORA_IOC_WR_OPMODE:
		{
			ret = sx127x_setopmode(data, arg, true);
			break;
		}
		case LORA_IOC_RD_OPMODE:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_WR_PAOUTPUT:
		{
			ret = sx127x_setpaoutput(data, arg);
			break;
		}
		case LORA_IOC_RD_PAOUTPUT:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_WR_SYNCWORD:
		{
			ret = sx127x_setsyncword(data, arg & 0xff);
			break;
		}
		case LORA_IOC_RD_SYNCWORD:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_WR_CRC:
		{
			//ret = sx127x_setcrc(data, arg & 0x1);
			int val = (int)arg;

			if(val)
			{
				data->cfg.LoRa.CrcOn = true;
			}else{
				data->cfg.LoRa.CrcOn = false;
			}
			break;
		}
		case LORA_IOC_RD_CRC:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_WR_INVERTIQ:
		{
			//ret = sx127x_setinvertiq(data, arg & 1);
			int val = (int)arg;

			if(val)
				data->cfg.LoRa.IqInverted = true;
			else
				data->cfg.LoRa.IqInverted = false;
			break;
		}
		case LORA_IOC_RD_INVERTIQ:
		{
			ret = 0;
			break;
		}
		case LORA_IOC_RD_FDEV:
		{
			break;
		}
		case LORA_IOC_WR_FDEV:
		{
			break;
		}
		case LORA_IOC_RD_PREAMBLELEN:
		{
			break;
		}
		case LORA_IOC_WR_PREAMBLELEN:
		{
			u16 val = (u16)arg;

			data->cfg.LoRa.PreambleLen = val;
			break;
		}
		default:
			ret = -EINVAL;
			break;
	}
	mutex_unlock(&data->mutex);
	return ret;
}

static struct file_operations drv_fops = {
		.open = drv_open,
		.read = drv_read,
		.write = drv_write,
		.release = drv_release,
		.unlocked_ioctl = drv_ioctl
};


static int sx127x_probe(struct spi_device *spi){
	int ret = 0;
	struct sx127x *data;
	u8 version;
	unsigned minor;

	// allocate all of the crap we need
	data = kmalloc(sizeof(*data), GFP_KERNEL);
	if(!data){
		DPRINTK("failed to allocate driver data\n");
		ret = -ENOMEM;
		goto err_allocdevdata;
	}

	data->open = 0;
    data->name = spi->modalias;
	//INIT_WORK(&data->irq_work, sx127x_irq_work_handler);
	INIT_LIST_HEAD(&data->device_entry);
	init_waitqueue_head(&data->readwq);
	init_waitqueue_head(&data->writewq);
	mutex_init(&data->mutex);
	data->fosc = 32000000; //TODO use value from DT
	data->cfg.pa = SX127X_PA_PABOOST; // TODO use value from DT
	data->spidevice = spi;
	data->opmode = SX127X_OPMODE_STANDBY;

	ret = kfifo_alloc(&data->out, PAGE_SIZE, GFP_KERNEL);
	if(ret){
		DPRINTK("failed to allocate out fifo\n");
		goto err_allocoutfifo;
	}

	ret = sx127x_parse_dt(&spi->dev, &data->plat_data);
	if(ret < 0)
	{
		goto err_resetgpio;
	}


	// get the rev from the chip and check it's what we expect
	sx127x_reg_read(spi, SX127X_REG_VERSION, &version);
	if(version != 0x12){
		dev_err(&spi->dev, "unknown chip version %x\n", version);
		ret = -EINVAL;
		goto err_chipid;
	}
	dev_warn(&spi->dev, "chip version %x\n",(unsigned) version);


	// create the frontend device and stash it in the spi device
	mutex_lock(&device_list_lock);
    minor = find_first_zero_bit(minors, DRV_MINOR);
    if (minor < DRV_MINOR) {
		minor = 0;
		data->devt = MKDEV(devmajor, minor);
		data->dev = device_create(devclass, &spi->dev, data->devt, data, "%s%d", DRV_NAME, minor);
		if(IS_ERR(data->dev)){
			DPRINTK("failed to create char device\n");
			ret = -ENOMEM;
			goto err_createdevice;
		}
		set_bit(minor, minors);
		list_add(&data->device_entry, &device_list);
    }
	mutex_unlock(&device_list_lock);
	spi_set_drvdata(spi, data);

	// setup sysfs nodes
	ret = device_create_file(data->chardevice, &dev_attr_modulation);
	ret = device_create_file(data->chardevice, &dev_attr_opmode);
	ret = device_create_file(data->chardevice, &dev_attr_carrierfrequency);
	ret = device_create_file(data->chardevice, &dev_attr_rssi);
	ret = device_create_file(data->chardevice, &dev_attr_paoutput);
	ret = device_create_file(data->chardevice, &dev_attr_outputpower);
	// these are LoRa specifc
	ret = device_create_file(data->chardevice, &dev_attr_sf);
	ret = device_create_file(data->chardevice, &dev_attr_bw);
	ret = device_create_file(data->chardevice, &dev_attr_codingrate);
	ret = device_create_file(data->chardevice, &dev_attr_implicitheadermodeon);

	return 0;

//err_sysfs:
//	device_destroy(devclass, data->devt);
err_createdevice:
	mutex_unlock(&device_list_lock);
//err_irq:
err_chipid:
err_resetgpio:
	kfifo_free(&data->out);
err_allocoutfifo:
	kfree(data);
err_allocdevdata:
	return ret;
}

static int sx127x_remove(struct spi_device *spi){
	struct sx127x *data = spi_get_drvdata(spi);

	device_remove_file(data->chardevice, &dev_attr_modulation);
	device_remove_file(data->chardevice, &dev_attr_opmode);
	device_remove_file(data->chardevice, &dev_attr_carrierfrequency);
	device_remove_file(data->chardevice, &dev_attr_rssi);
	device_remove_file(data->chardevice, &dev_attr_paoutput);
	device_remove_file(data->chardevice, &dev_attr_outputpower);

	device_remove_file(data->chardevice, &dev_attr_sf);
	device_remove_file(data->chardevice, &dev_attr_bw);
	device_remove_file(data->chardevice, &dev_attr_codingrate);
	device_remove_file(data->chardevice, &dev_attr_implicitheadermodeon);

	clear_bit(MINOR(data->devt), minors);

	device_destroy(devclass, data->devt);
	
	kfifo_free(&data->out);
	kfree(data);

	return 0;
}

static const struct of_device_id sx127x_of_match[] = {
	{
		.compatible = "semtech, sx127x",
	},
	{ },
};
MODULE_DEVICE_TABLE(of, sx127x_of_match);


static struct spi_driver sx127x_driver = {
	.probe		= sx127x_probe,
	.remove		= sx127x_remove,
	.driver = {
		.name	= SX127X_DRIVERNAME,
		.of_match_table = of_match_ptr(sx127x_of_match),
		.owner = THIS_MODULE,
	},
};

static int __init sx127x_init(void)
{
	int result = 0;
    //申请设备号
    result = register_chrdev_region(drv_dev_num, DRV_MINOR, DRV_NAME);
    if (result)
    {
        goto ERR_EXIT;
    }
    
    //注册字符设备
    cdev_init(&drv_cdev, &drv_fops);
    drv_cdev.owner = THIS_MODULE;
    result = cdev_add(&drv_cdev, drv_dev_num, DRV_MINOR);
    if (result)   
    {        
        goto ERR_EXIT0;    
    }
    
    //创建设备节点    
    drv_class = class_create(THIS_MODULE, DRV_NAME);    
    if (drv_class == NULL) 
    {        
        result = -ENOMEM;        
        goto ERR_EXIT1;    
    }

    result = spi_register_driver(&sx127x_driver);
    if (result < 0)
    {
        goto ERR_EXIT2;
    }

    return result;
ERR_EXIT2:
    class_destroy(drv_class);
ERR_EXIT1:
    cdev_del(&drv_cdev);
ERR_EXIT0:
    unregister_chrdev_region(drv_dev_num, DRV_MINOR);
ERR_EXIT:    
    return result;
}
module_init(sx127x_init);

static void __exit sx127x_exit(void)
{
	spi_unregister_driver(&sx127x_driver);
    cdev_del(&drv_cdev);
    class_destroy(drv_class);
	drv_class = NULL;
	unregister_chrdev_region(drv_dev_num, DRV_MINOR);
}
module_exit(sx127x_exit);

MODULE_LICENSE("GPL");
