/*!
 * \file      sx1278.c
 *
 * \brief     SX1278 driver implementation
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \author    Miguel Luis ( Semtech )
 *
 * \author    Gregory Cristian ( Semtech )
 *
 * \author    Wael Guibene ( Semtech )
 *
 * \author    pengrui (Beijing Carsmart)
 */
#include <linux/types.h>
#include <linux/delay.h>
#include "sx1278.h"
#include "drv_lib.h"

/*
static struct spi_device *spi_ptr = NULL;

static LoRa_Config_st_ptr sx1278_cfg_ptr;

static int8_t RxPacketSnrEstimate;
static int8_t RxPacketRssiValue;
static uint8_t RxGain = 1;
static uint32_t RxTimeoutTimer = 0;
*/

/*!
 * \brief Radio hardware registers initialization definition
 *
 * \remark Can be automatically generated by the SX1272 GUI (not yet implemented)
 */
#define RADIO_INIT_REGISTERS_VALUE                \
{                                                 \
    { MODEM_FSK , REG_LNA                , 0x23 },\
    { MODEM_FSK , REG_RXCONFIG           , 0x1E },\
    { MODEM_FSK , REG_RSSICONFIG         , 0xD2 },\
    { MODEM_FSK , REG_AFCFEI             , 0x01 },\
    { MODEM_FSK , REG_PREAMBLEDETECT     , 0xAA },\
    { MODEM_FSK , REG_OSC                , 0x07 },\
    { MODEM_FSK , REG_SYNCCONFIG         , 0x12 },\
    { MODEM_FSK , REG_SYNCVALUE1         , 0xC1 },\
    { MODEM_FSK , REG_SYNCVALUE2         , 0x94 },\
    { MODEM_FSK , REG_SYNCVALUE3         , 0xC1 },\
    { MODEM_FSK , REG_PACKETCONFIG1      , 0xD8 },\
    { MODEM_FSK , REG_FIFOTHRESH         , 0x8F },\
    { MODEM_FSK , REG_IMAGECAL           , 0x02 },\
    { MODEM_FSK , REG_DIOMAPPING1        , 0x00 },\
    { MODEM_FSK , REG_DIOMAPPING2        , 0x30 },\
    { MODEM_LORA, REG_LR_DETECTOPTIMIZE  , 0x43 },\
    { MODEM_LORA, REG_LR_PAYLOADMAXLENGTH, 0x40 },\
}                                                 \

/*!
 * Radio hardware registers initialization
 *
 * \remark RADIO_INIT_REGISTERS_VALUE is defined in sx1278-board.h file
 */
const RadioRegisters_st RadioRegsInit[] = RADIO_INIT_REGISTERS_VALUE;

/*!
 * Frequency hopping frequencies table
 */
const int32_t HoppingFrequencies[] =
{
    916500000,
    923500000,
    906500000,
    917500000,
    917500000,
    909000000,
    903000000,
    916000000,
    912500000,
    926000000,
    925000000,
    909500000,
    913000000,
    918500000,
    918500000,
    902500000,
    911500000,
    926500000,
    902500000,
    922000000,
    924000000,
    903500000,
    913000000,
    922000000,
    926000000,
    910000000,
    920000000,
    922500000,
    911000000,
    922000000,
    909500000,
    926000000,
    922000000,
    918000000,
    925500000,
    908000000,
    917500000,
    926500000,
    908500000,
    916000000,
    905500000,
    916000000,
    903000000,
    905000000,
    915000000,
    913000000,
    907000000,
    910000000,
    926500000,
    925500000,
    911000000,
};

int SX1278_Read_Reg(struct spi_device *spi_ptr, uint8_t addr, uint8_t *data_ptr)
{
    int result = 0;
    uint8_t reg = (addr & 0x7F);

    if((NULL == spi_ptr) || (NULL == data_ptr))
    {
        printk(KERN_ERR "%s %d error %d reading %x\n", __FUNCTION__, __LINE__, result, addr);
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = spi_write_then_read(spi_ptr, &reg, 1, data_ptr, 1);
    if (result < 0)
    {
        printk(KERN_ERR "%s %d error %d reading %x\n", __FUNCTION__, __LINE__, result, addr);
        goto ERR_EXIT;
    }

ERR_EXIT:
    
    return result;
}

int SX1278_Write_Reg(struct spi_device *spi_ptr, uint8_t addr, uint8_t data)
{
    int result = 0;
    uint8_t data_buf[2] = {0};
    
    data_buf[0] = (addr | 0x80);
    data_buf[1] = data;

    if(NULL == spi_ptr)
    {
        printk(KERN_ERR "%s %d error %d\n", __FUNCTION__, __LINE__, result);
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = spi_write(spi_ptr, (void *)data_buf, 2);
    if (result < 0)
    {
        printk(KERN_ERR "%s %d write %d\n", __FUNCTION__, __LINE__, result);
        goto ERR_EXIT;
    }

ERR_EXIT:    

    return result;
}

int SX1278_Read_FIFO(struct spi_device *spi_ptr, uint8_t *data_ptr, uint8_t data_len)
{
    int result = 0;
    uint8_t reg = (0x00&0x7F);
    
    if((NULL == spi_ptr) || (NULL == data_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = spi_write_then_read(spi_ptr, &reg, 1, data_ptr, data_len);
    if (result < 0)
    {
        printk(KERN_ERR "%s %d error %d reading %x\n", __FUNCTION__, __LINE__, result, reg);
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
#if 0
    uint8_t reg = (0x00&0x7F);
    struct spi_transfer t[2] = {{0}, {0}};
    struct spi_message m = {{0}};

    if((NULL == spi_ptr) || (NULL == data_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    pdata = kzalloc((data_len + 1), GFP_KERNEL);
    if (!pdata) 
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    spi_message_init(&m);
    
    t[0].tx_buf = &reg;
    t[0].len = 1;

    t[1].rx_buf = data_ptr;
    t[1].len = data_len ;
    
    spi_message_add_tail(t, &m);

    spi_sync(spi_ptr, &m);

    result += m.actual_length - 1;

ERR_EXIT:
    if(pdata)
        kfree(pdata);
    return result;
#endif
}

int SX1278_Write_FIFO(struct spi_device *spi_ptr, uint8_t *data_ptr, uint8_t data_len)
{
    int result = 0;
    uint8_t *pdata = NULL;
    struct spi_transfer t = {0};
    struct spi_message m = {{0}};

    if((NULL == spi_ptr) || (NULL == data_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    pdata = kzalloc((data_len + 1), GFP_KERNEL);
    if (!pdata) 
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    pdata[0] = 0x80;
    memcpy(&pdata[1], data_ptr, data_len);

    spi_message_init(&m);
    
    t.tx_buf = pdata;
    t.len = (data_len + 1);
    
    spi_message_add_tail(&t, &m);

    spi_sync(spi_ptr, &m);

    result += m.actual_length - 1;
    
ERR_EXIT:

    if(pdata)
        kfree(pdata);
    
    return result;
}


int SX1278LoRaInit(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetDefaults(sx1278_ptr);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetLNA(sx1278_ptr, RFLR_LNA_GAIN_G1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    // set the Rx RF settings 
    result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    // SF6 only operates in implicit header mode. 
    result = SX1278LoRaSetSpreadingFactor(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.SpreadingFactor);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetErrorCoding(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.ErrorCoding);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetPacketCrcOn(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.CrcOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetSignalBandwidth(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.SignalBw);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetImplicitHeaderOn(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.ImplicitHeaderOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetSymbTimeout(sx1278_ptr, 0x3FF);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetPayloadLength(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.PayloadLength);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetLowDatarateOptimize(sx1278_ptr, true);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if( sx1278_ptr->cfg.tx_cfg.RFFrequency > 860000000 )
    {
        result = SX1278LoRaSetPAOutput(sx1278_ptr, RFLR_PACONFIG_PASELECT_PABOOST);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278LoRaSetPa20dBm(sx1278_ptr, true);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        sx1278_ptr->cfg.tx_cfg.Power = 20;
        result = SX1278LoRaSetRFPower(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.Power);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }
    else
    {
        result = SX1278LoRaSetPAOutput(sx1278_ptr, RFLR_PACONFIG_PASELECT_RFO);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278LoRaSetPa20dBm(sx1278_ptr, false);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        sx1278_ptr->cfg.tx_cfg.Power = 14;
        result = SX1278LoRaSetRFPower(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.Power);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    } 

    result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_STANDBY);

ERR_EXIT:

    return result;
}

int SX1278LoRaSetDefaults(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        goto ERR_EXIT;
    }
    // REMARK: See SX1278 datasheet for modified default values.


ERR_EXIT:

    return result;
}

int SX1278LoRaGetVersion(SX1278_st_ptr sx1278_ptr, uint8_t version)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_VERSION, &version);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaSetOpMode(SX1278_st_ptr sx1278_ptr, uint8_t opMode)
{
    int result = 0;
    uint8_t RegOpMode = 0;
    uint8_t opModePrev = RFLR_OPMODE_STANDBY;
    bool antennaSwitchTxOnPrev = true;
    bool antennaSwitchTxOn = false;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaGetOpMode(sx1278_ptr, &opModePrev);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if( opMode != opModePrev )
    {
        if( opMode == RFLR_OPMODE_TRANSMITTER )
        {
            antennaSwitchTxOn = true;
        }
        else
        {
            antennaSwitchTxOn = false;
        }
        
        if( antennaSwitchTxOn != antennaSwitchTxOnPrev )
        {
            antennaSwitchTxOnPrev = antennaSwitchTxOn;
            //RXTX( antennaSwitchTxOn ); // Antenna switch control
        }
        
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, &RegOpMode);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
 
        RegOpMode = ( RegOpMode & RFLR_OPMODE_MASK ) | opMode;
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, RegOpMode);   
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

ERR_EXIT:
    
    return result;
}

int SX1278LoRaGetOpMode(SX1278_st_ptr sx1278_ptr, uint8_t *opmode)
{
    int result = 0;
    uint8_t RegOpMode = 0;

    if((NULL == sx1278_ptr)||(NULL == opmode))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, &RegOpMode);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *opmode = RegOpMode & ~RFLR_OPMODE_MASK;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetModem(SX1278_st_ptr sx1278_ptr, RadioModems_en modem)
{
    int result = 0;
    uint8_t regval = 0;
    RadioModems_en curmodem;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278LoRaGetModem(sx1278_ptr, &curmodem);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(curmodem != modem)
    {
        result = SX1278SetOpMode(sx1278_ptr, RFLR_OPMODE_SLEEP);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        switch(modem)
        {
        default:
        case MODEM_FSK:
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, (regval&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_OFF);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, 0x00);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING2, 0x30); // DIO5=ModeReady
            if(result < 0)
            {
                goto ERR_EXIT;
            }
        
            break;
        case MODEM_LORA:
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, (regval&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_ON);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, 0x00);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
        
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING2, 0x00);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
        
            break;
        }
    }

ERR_EXIT:
   
    return result;
}

int SX1278LoRaGetModem(SX1278_st_ptr sx1278_ptr, RadioModems_en *modem)
{
    int result = 0;
    uint8_t RegOpMode = 0;

    if((NULL == sx1278_ptr) || (NULL == modem))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, &RegOpMode);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *modem = (RegOpMode & ~RFLR_MODEM_MASK) ? MODEM_LORA : MODEM_FSK;

ERR_EXIT:
   
    return result;
}

int SX1278LoRaReadRxGain(SX1278_st_ptr sx1278_ptr, uint8_t *RxGain)
{
    int result = 0;
    uint8_t val = 0x00;
    
    if((NULL == sx1278_ptr)||(NULL == RxGain))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_LNA, &val);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *RxGain = ( val >> 5 ) & 0x07;

ERR_EXIT:

    return result;
}

int SX1278LoRaReadRssi(SX1278_st_ptr sx1278_ptr, uint32_t freq, int8_t *Rssi)
{
    int result = 0;
    uint8_t val = 0x00;

    if((NULL == sx1278_ptr)||(NULL == Rssi))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    // Reads the RSSI value
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_RSSIVALUE, &val);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(freq < 860000000)  // LF
    {
        *Rssi = RSSI_OFFSET_LF + val;
    }
    else
    {
        *Rssi = RSSI_OFFSET_HF + val;
    }

ERR_EXIT:

    return result;    
}
/*
uint8_t SX1278LoRaGetPacketRxGain( void )
{
    return RxGain;
}

int8_t SX1278LoRaGetPacketSnr( void )
{
    return RxPacketSnrEstimate;
}

int8_t SX1278LoRaGetPacketRssi( void )
{
    return RxPacketRssiValue;
}
*/
int SX1278LoRaSetLNA(SX1278_st_ptr sx1278_ptr, uint8_t val)
{
    int result = 0;

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_LNA, val);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:
   
    return result;
}

int SX1278LoRaSetRFFrequency(SX1278_st_ptr sx1278_ptr, uint32_t freq)
{
    int result = 0;
    uint8_t regmsb = 0;
    uint8_t regmid = 0;
    uint8_t reglsb = 0;
    uint64_t temp = 0;
    uint64_t freq_step = FREQ_STEP;    
    uint32_t step = 0;    

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    do_div(freq_step, 5);   
    step = (uint32_t)freq_step;
 
    temp = (uint64_t)freq * 100000000;
    do_div(temp, step);
    
    freq = ( uint32_t )temp / 5;
    
    regmsb = ( uint8_t )( ( freq >> 16 ) & 0xFF );
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFMSB, regmsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    regmid = ( uint8_t )( ( freq >> 8 ) & 0xFF );
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFMID, regmid);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    reglsb = ( uint8_t )( freq & 0xFF );
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFLSB, reglsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetRFFrequency(SX1278_st_ptr sx1278_ptr, uint32_t *RFFrequency)
{
    int result = 0;
    uint8_t RegFrfMsb = 0;
    uint8_t RegFrfMid = 0;
    uint8_t RegFrfLsb = 0;
    uint64_t temp = 0;

    if((NULL == sx1278_ptr) || (NULL == RFFrequency))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFMSB, &RegFrfMsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFMID, &RegFrfMid);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_FRFLSB, &RegFrfLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    temp = ((uint32_t)RegFrfMsb<<16)|((uint32_t)RegFrfMid<<8)|((uint32_t)RegFrfLsb); 
    temp *= FREQ_STEP;

    do_div(temp, 100000000);
    *RFFrequency = (uint32_t)temp;

ERR_EXIT:
    
    return result;
}

uint8_t SX1278GetPaSelect( uint32_t channel )
{
    if( channel < RF_MID_BAND_THRESH )
    {
        return RF_PACONFIG_PASELECT_PABOOST;
    }
    else
    {
        return RF_PACONFIG_PASELECT_RFO;
    }
}

int SX1278SetRfTxPower(SX1278_st_ptr sx1278_ptr,uint32_t freq, int power)
{
    int result = 0;
    uint8_t paConfig = 0;
    uint8_t paDac = 0;

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr ,REG_PACONFIG, &paConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr ,REG_PADAC, &paDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    paConfig = ( paConfig & RF_PACONFIG_PASELECT_MASK ) | SX1278GetPaSelect(freq);
    paConfig = ( paConfig & RF_PACONFIG_MAX_POWER_MASK ) | 0x70;

    if( ( paConfig & RF_PACONFIG_PASELECT_PABOOST ) == RF_PACONFIG_PASELECT_PABOOST )
    {
        if( power > 17 )
        {
            paDac = ( paDac & RF_PADAC_20DBM_MASK ) | RF_PADAC_20DBM_ON;
        }
        else
        {
            paDac = ( paDac & RF_PADAC_20DBM_MASK ) | RF_PADAC_20DBM_OFF;
        }
        if( ( paDac & RF_PADAC_20DBM_ON ) == RF_PADAC_20DBM_ON )
        {
            if( power < 5 )
            {
                power = 5;
            }
            if( power > 20 )
            {
                power = 20;
            }
            paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( uint8_t )( ( uint16_t )( power - 5 ) & 0x0F );
        }
        else
        {
            if( power < 2 )
            {
                power = 2;
            }
            if( power > 17 )
            {
                power = 17;
            }
            paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( uint8_t )( ( uint16_t )( power - 2 ) & 0x0F );
        }
    }
    else
    {
        if( power < -1 )
        {
            power = -1;
        }
        if( power > 14 )
        {
            power = 14;
        }
        paConfig = ( paConfig & RF_PACONFIG_OUTPUTPOWER_MASK ) | ( uint8_t )( ( uint16_t )( power + 1 ) & 0x0F );
    }
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_PACONFIG, paConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_PADAC, paDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaSetRFPower(SX1278_st_ptr sx1278_ptr, int8_t power)
{
    int result = 0;
    uint8_t RegPaConfig = 0;
    uint8_t RegPaDac = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, &RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PADAC, &RegPaDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if((RegPaConfig & RFLR_PACONFIG_PASELECT_PABOOST) == RFLR_PACONFIG_PASELECT_PABOOST)
    {
        if((RegPaDac & 0x87) == 0x87)
        {
            if( power < 5 )
            {
                power = 5;
            }
            if( power > 20 )
            {
                power = 20;
            }
            RegPaConfig = (RegPaConfig & RFLR_PACONFIG_MAX_POWER_MASK) | 0x70;
            RegPaConfig = (RegPaConfig & RFLR_PACONFIG_OUTPUTPOWER_MASK) | (uint8_t)((uint16_t)(power - 5) & 0x0F);
        }
        else
        {
            if(power < 2)
            {
                power = 2;
            }
            if(power > 17)
            {
                power = 17;
            }
            RegPaConfig = (RegPaConfig & RFLR_PACONFIG_MAX_POWER_MASK) | 0x70;
            RegPaConfig = (RegPaConfig & RFLR_PACONFIG_OUTPUTPOWER_MASK) | (uint8_t)((uint16_t)(power - 2) & 0x0F);
        }
    }
    else
    {
        if(power < -1)
        {
            power = -1;
        }
        if(power > 14)
        {
            power = 14;
        }
        RegPaConfig = (RegPaConfig & RFLR_PACONFIG_MAX_POWER_MASK) | 0x70;
        RegPaConfig = (RegPaConfig & RFLR_PACONFIG_OUTPUTPOWER_MASK) | (uint8_t)((uint16_t)(power + 1) & 0x0F);
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetRFPower(SX1278_st_ptr sx1278_ptr, int8_t *power)
{
    int result = 0;
    uint8_t RegPaConfig = 0;
    uint8_t RegPaDac = 0;

    if((NULL == sx1278_ptr) || (NULL == power))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, &RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PADAC, &RegPaDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if((RegPaConfig & RFLR_PACONFIG_PASELECT_PABOOST) == RFLR_PACONFIG_PASELECT_PABOOST)
    {
        if((RegPaDac & 0x07) == 0x07)
        {
            *power = 5 + (RegPaConfig & ~RFLR_PACONFIG_OUTPUTPOWER_MASK);
        }
        else
        {
            *power = 2 + (RegPaConfig & ~RFLR_PACONFIG_OUTPUTPOWER_MASK);
        }
    }
    else
    {
        *power = -1 + (RegPaConfig & ~RFLR_PACONFIG_OUTPUTPOWER_MASK);
    }

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetSignalBandwidth(SX1278_st_ptr sx1278_ptr, uint8_t bw)
{
    int result = 0;
    uint8_t RegModemConfig1 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegModemConfig1 = (RegModemConfig1&RFLR_MODEMCONFIG1_BW_MASK)|(bw<<4);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetSignalBandwidth(SX1278_st_ptr sx1278_ptr, uint8_t *SignalBw)
{
    int result = 0;
    uint8_t RegModemConfig1 = 0;

    if((NULL == sx1278_ptr) || (NULL == SignalBw))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *SignalBw = (RegModemConfig1&~RFLR_MODEMCONFIG1_BW_MASK) >> 4;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetSpreadingFactor(SX1278_st_ptr sx1278_ptr, uint8_t factor)
{
    int result = 0;
    uint8_t RegModemConfig2 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    if(factor > 12)
    {
        factor = 12;
    }
    else if(factor < 6)
    {
        factor = 6;
    }

    if(factor == 6)
    {
        result = SX1278LoRaSetNbTrigPeaks(sx1278_ptr, 5);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278LoRaSetNbTrigPeaks(sx1278_ptr, 3);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegModemConfig2 = (RegModemConfig2&RFLR_MODEMCONFIG2_SF_MASK)|(factor<<4);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetSpreadingFactor(SX1278_st_ptr sx1278_ptr, uint8_t *SpreadingFactor)
{
    int result = 0;
    uint8_t RegModemConfig2 = 0;

    if((NULL == sx1278_ptr) || (NULL == SpreadingFactor))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2 );
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *SpreadingFactor = (RegModemConfig2 & ~RFLR_MODEMCONFIG2_SF_MASK ) >> 4;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetErrorCoding(SX1278_st_ptr sx1278_ptr, uint8_t value)
{
    int result = 0;
    uint8_t RegModemConfig1 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegModemConfig1 = (RegModemConfig1&RFLR_MODEMCONFIG1_CODINGRATE_MASK)|(value<<1);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetErrorCoding(SX1278_st_ptr sx1278_ptr, uint8_t *ErrorCoding)
{
    int result = 0;
    uint8_t RegModemConfig1 = 0;

    if((NULL == sx1278_ptr) || (NULL == ErrorCoding))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *ErrorCoding = (RegModemConfig1 & ~RFLR_MODEMCONFIG1_CODINGRATE_MASK) >> 1;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetPacketCrcOn(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;
    uint8_t RegModemConfig2 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2 );
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    RegModemConfig2 = (RegModemConfig2&RFLR_MODEMCONFIG2_RXPAYLOADCRC_MASK )|(enable<<2);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result; 
}

int SX1278LoRaSetPreambleLength(SX1278_st_ptr sx1278_ptr, uint16_t value)
{
    int result = 0;
    uint8_t RegPreambleMsb = 0;
    uint8_t RegPreambleLsb = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    RegPreambleMsb = ( value >> 8 ) & 0x00FF;
    RegPreambleLsb = value & 0xFF;
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PREAMBLEMSB, RegPreambleMsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PREAMBLELSB, RegPreambleLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetPreambleLength(SX1278_st_ptr sx1278_ptr, uint16_t *PreambleLen)
{
    int result = 0;
    uint8_t RegPreambleMsb = 0;
    uint8_t RegPreambleLsb = 0;

    if((NULL == sx1278_ptr) || (NULL == PreambleLen))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PREAMBLEMSB, &RegPreambleMsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PREAMBLELSB, &RegPreambleLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *PreambleLen = ( ( RegPreambleMsb & 0x00FF ) << 8 ) | RegPreambleLsb;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaGetPacketCrcOn(SX1278_st_ptr sx1278_ptr, bool *CrcOn)
{
    int result = 0;    
    uint8_t RegModemConfig2 = 0;

    if((NULL == sx1278_ptr) || (NULL == CrcOn))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
        
    *CrcOn = (RegModemConfig2 & RFLR_MODEMCONFIG2_RXPAYLOADCRC_ON ) >> 1;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetImplicitHeaderOn(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;
    uint8_t RegModemConfig1 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegModemConfig1 = (RegModemConfig1&RFLR_MODEMCONFIG1_IMPLICITHEADER_MASK)|(enable);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetImplicitHeaderOn(SX1278_st_ptr sx1278_ptr, bool *ImplicitHeaderOn)
{
    int result = 0;
    uint8_t RegModemConfig1 =0;

    if((NULL == sx1278_ptr) || (NULL == ImplicitHeaderOn))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG1, &RegModemConfig1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *ImplicitHeaderOn = (RegModemConfig1&RFLR_MODEMCONFIG1_IMPLICITHEADER_ON) ? true : false;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetRxSingleOn(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //LoRaSettings.RxSingleOn = enable;
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaGetRxSingleOn(SX1278_st_ptr sx1278_ptr, bool *RxSingleOn)
{
    int result = 0;

    if((NULL == sx1278_ptr) || (NULL == RxSingleOn))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    *RxSingleOn = true;
    
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaSetFreqHopOn(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;
    uint8_t regval = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    if(enable)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PLLHOP, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PLLHOP, (regval&RFLR_PLLHOP_FASTHOP_MASK)|RFLR_PLLHOP_FASTHOP_ON);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    
ERR_EXIT:
    
    return result;     
}

int SX1278LoRaGetFreqHopOn(SX1278_st_ptr sx1278_ptr, bool *FreqHopOn)
{
    int result = 0;
    uint8_t regval = 0;

    if((NULL == sx1278_ptr) || (NULL == FreqHopOn))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PLLHOP, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    *FreqHopOn = (regval & RFLR_PLLHOP_FASTHOP_ON);
    
ERR_EXIT:

    return result;
}

int SX1278LoRaSetHopPeriod(SX1278_st_ptr sx1278_ptr, uint8_t value)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_HOPPERIOD, value);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
ERR_EXIT:

    return result;    
}

int SX1278LoRaGetHopPeriod(SX1278_st_ptr sx1278_ptr, uint8_t *HopPeriod)
{
    int result = 0;
    uint8_t RegHopPeriod =0;

    if((NULL == sx1278_ptr) || (NULL == HopPeriod))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_HOPPERIOD, &RegHopPeriod);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *HopPeriod = RegHopPeriod;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetTxPacketTimeout(SX1278_st_ptr sx1278_ptr, uint32_t value)
{
    int result = 0;
    //LoRaSettings.TxPacketTimeout = value;
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    sx1278_ptr->cfg.tx_cfg.TxPacketTimeout = value;
ERR_EXIT:
    
    return result;
}

int SX1278LoRaGetTxPacketTimeout(SX1278_st_ptr sx1278_ptr, uint32_t *TxPacketTime)
{
    int result = 0;

    if((NULL == sx1278_ptr) || (NULL == TxPacketTime))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    *TxPacketTime = sx1278_ptr->cfg.tx_cfg.TxPacketTimeout;
    
ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetRxPacketTimeout(SX1278_st_ptr sx1278_ptr, uint32_t value)
{
    int result = 0;
    //LoRaSettings.RxPacketTimeout = value;
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
 
    sx1278_ptr->cfg.rx_cfg.RxPacketTimeout = value;
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaGetRxPacketTimeout(SX1278_st_ptr sx1278_ptr, uint32_t *RxPacketTime)
{
    int result = 0;

    if((NULL == sx1278_ptr) || (NULL == RxPacketTime))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //return LoRaSettings.RxPacketTimeout;
    *RxPacketTime = sx1278_ptr->cfg.rx_cfg.RxPacketTimeout;
    
ERR_EXIT:
    
    return result;

}

int SX1278LoRaSetPayloadLength(SX1278_st_ptr sx1278_ptr, uint8_t value)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PAYLOADLENGTH, value);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetPayloadLength(SX1278_st_ptr sx1278_ptr, uint8_t *PayloadLength)
{
    int result = 0;
    uint8_t RegPayloadLength = 0;

    if((NULL == sx1278_ptr) || (NULL == PayloadLength))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PAYLOADLENGTH, &RegPayloadLength);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *PayloadLength = RegPayloadLength;
ERR_EXIT:

    return result;
}

int SX1278LoRaGetTxConfig(SX1278_st_ptr sx1278_ptr, SX1278_Tx_Config_st_ptr cfg_ptr)
{
    int result = 0;
    
    if((NULL == sx1278_ptr) || (NULL == cfg_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    memcpy(cfg_ptr, &sx1278_ptr->cfg.tx_cfg, SX1278_TX_CONFIG_ST_LEN);
ERR_EXIT:

    return result;

}

int SX1278LoRaSetTxConfig(SX1278_st_ptr sx1278_ptr, SX1278_Tx_Config_st_ptr cfg_ptr)
{
    int result = 0;
    
    if((NULL == sx1278_ptr) || (NULL == cfg_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    memcpy(&sx1278_ptr->cfg.rx_cfg, cfg_ptr, SX1278_TX_CONFIG_ST_LEN);
ERR_EXIT:

    return result;
}

int SX1278LoRaGetRxConfig(SX1278_st_ptr sx1278_ptr, SX1278_Rx_Config_st_ptr cfg_ptr)
{
    int result = 0;
    
    if((NULL == sx1278_ptr) || (NULL == cfg_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    memcpy(cfg_ptr, &sx1278_ptr->cfg.rx_cfg, SX1278_RX_CONFIG_ST_LEN);
ERR_EXIT:

    return result;

}

int SX1278LoRaSetRxConfig(SX1278_st_ptr sx1278_ptr, SX1278_Rx_Config_st_ptr cfg_ptr)
{
    int result = 0;
    
    if((NULL == sx1278_ptr) || (NULL == cfg_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    memcpy(&sx1278_ptr->cfg.tx_cfg, cfg_ptr, SX1278_RX_CONFIG_ST_LEN);
ERR_EXIT:

    return result;
}


int SX1278LoRaSetPa20dBm(SX1278_st_ptr sx1278_ptr, bool enale)
{
    int result = 0;
    uint8_t RegPaDac = 0;
    uint8_t RegPaConfig = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PADAC, &RegPaDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, &RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }    

    if( (RegPaConfig & RFLR_PACONFIG_PASELECT_PABOOST ) == RFLR_PACONFIG_PASELECT_PABOOST )
    {    
        if( enale == true )
        {
            RegPaDac = 0x87;
        }
    }
    else
    {
        RegPaDac = 0x84;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PADAC, RegPaDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetPa20dBm(SX1278_st_ptr sx1278_ptr, bool *Pa20dBm)
{
    int result = 0;
    uint8_t RegPaDac = 0;

    if((NULL == sx1278_ptr) || (NULL == Pa20dBm))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PADAC, &RegPaDac);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *Pa20dBm = ( ( RegPaDac & 0x07 ) == 0x07 ) ? true : false;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetPAOutput(SX1278_st_ptr sx1278_ptr, uint8_t outputPin)
{
    int result = 0;
    uint8_t RegPaConfig = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
        
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, &RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegPaConfig = (RegPaConfig&RFLR_PACONFIG_PASELECT_MASK)|outputPin;
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetPAOutput(SX1278_st_ptr sx1278_ptr, uint8_t *PAOutput)
{
    int result = 0;
    uint8_t RegPaConfig = 0;

    if((NULL == sx1278_ptr) || (NULL == PAOutput))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PACONFIG, &RegPaConfig);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *PAOutput = RegPaConfig & ~RFLR_PACONFIG_PASELECT_MASK;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetPaRamp(SX1278_st_ptr sx1278_ptr, uint8_t value)
{
    int result = 0;
    uint8_t RegPaRamp = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PARAMP, &RegPaRamp);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegPaRamp = (RegPaRamp & RFLR_PARAMP_MASK ) | ( value & ~RFLR_PARAMP_MASK);
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PARAMP, RegPaRamp);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetPaRamp(SX1278_st_ptr sx1278_ptr, uint8_t *PaRamp)
{
    int result = 0;
    uint8_t RegPaRamp = 0;

    if((NULL == sx1278_ptr) || (NULL == PaRamp))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PARAMP, &RegPaRamp);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *PaRamp = RegPaRamp & ~RFLR_PARAMP_MASK;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetSymbTimeout(SX1278_st_ptr sx1278_ptr, uint16_t value)
{
    int result = 0;
    uint8_t RegModemConfig2 = 0;
    uint8_t RegSymbTimeoutLsb = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_SYMBTIMEOUTLSB, &RegSymbTimeoutLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    RegModemConfig2 = (RegModemConfig2&RFLR_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK)|((value>>8)&~RFLR_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK);
    RegSymbTimeoutLsb = value&0xFF;

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_SYMBTIMEOUTLSB, RegSymbTimeoutLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

uint16_t SX1278LoRaGetSymbTimeout(SX1278_st_ptr sx1278_ptr, uint16_t *SymbTimeout)
{
    int result = 0;
    uint8_t RegModemConfig2 = 0;
    uint8_t RegSymbTimeoutLsb = 0;

    if((NULL == sx1278_ptr) || (NULL == SymbTimeout))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG2, &RegModemConfig2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_SYMBTIMEOUTLSB, &RegSymbTimeoutLsb);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *SymbTimeout = ((RegModemConfig2&~RFLR_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK)<<8)|RegSymbTimeoutLsb;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetLowDatarateOptimize(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;
    uint8_t RegModemConfig3 =0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result= SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG3, &RegModemConfig3);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegModemConfig3 = (RegModemConfig3&RFLR_MODEMCONFIG3_LOWDATARATEOPTIMIZE_MASK)|(enable<<3);
    result= SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG3, RegModemConfig3);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetLowDatarateOptimize(SX1278_st_ptr sx1278_ptr, bool *LowDatarateOptimize)
{
    int result = 0;
    uint8_t RegModemConfig3 = 0;

    if((NULL == sx1278_ptr) || (NULL == LowDatarateOptimize))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_MODEMCONFIG3, &RegModemConfig3);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *LowDatarateOptimize = ((RegModemConfig3&RFLR_MODEMCONFIG3_LOWDATARATEOPTIMIZE_ON)>>3) ? true : false;

ERR_EXIT:
    
    return result;
}

int SX1278LoRaSetNbTrigPeaks(SX1278_st_ptr sx1278_ptr, uint8_t value)
{
    int result = 0;
    uint8_t RegDetectOptimize = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &RegDetectOptimize);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    RegDetectOptimize = (RegDetectOptimize & 0xF8)|value;
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, RegDetectOptimize);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278LoRaGetNbTrigPeaks(SX1278_st_ptr sx1278_ptr, uint8_t *NbTrigPeaks)
{
    int result= 0;
    uint8_t RegDetectOptimize = 0;

    if((NULL == sx1278_ptr) || (NULL == NbTrigPeaks))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, 0x31, &RegDetectOptimize);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    *NbTrigPeaks = (RegDetectOptimize & 0x07 );
    
ERR_EXIT:
    
    return result;
}


int SX1278LoRaStartRx(SX1278_st_ptr sx1278_ptr)
{
    int result= 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //SX1278LoRaSetRFState( RFLR_STATE_RX_INIT );
    
ERR_EXIT:
    
    return result;    
}


int SX1278LoRaGetRxPacket(SX1278_st_ptr sx1278_ptr, void *buffer_ptr, uint8_t buffer_len)
{
    int result= 0;
    uint8_t size = 0;
    uint8_t readsize = 0;
    uint8_t addr = 0;
    uint8_t regval = 0;
    
    if((NULL == sx1278_ptr) || (NULL == buffer_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_RXNBBYTES, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    size = regval;

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFORXCURRENTADDR, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    addr = regval;
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, addr);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    readsize = (size > buffer_len) ? buffer_len : size;
    
    result = SX1278_Read_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, readsize);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = readsize;
    
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaSetTxPacket(SX1278_st_ptr sx1278_ptr, const void *buffer, uint16_t size)
{
    int result= 0;

    if((NULL == sx1278_ptr) || (NULL == buffer))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //TxPacketSize = size;
    //memcpy( ( void * )RFBuffer, buffer, ( size_t )TxPacketSize); 
    //
    //RFLRState = RFLR_STATE_TX_INIT;
    
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaGetRFState(SX1278_st_ptr sx1278_ptr, uint8_t *RFState)
{
    int result= 0;

    if((NULL == sx1278_ptr) || (NULL == RFState))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //SX1278LoRaSetRFState( RFLR_STATE_RX_INIT );
    
ERR_EXIT:
    
    return result;    
}

int SX1278LoRaSetRFState(SX1278_st_ptr sx1278_ptr, uint8_t state)
{    
    int result= 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    //RFLRState = state;
    
ERR_EXIT:
    
    return result;    
}

/*!
 * \brief Process the LoRa modem Rx and Tx state machines depending on the
 *        SX1278 operating mode.
 *
 * \retval rfState Current RF state [RF_IDLE, RF_BUSY, 
 *                                   RF_RX_DONE, RF_RX_TIMEOUT,
 *                                   RF_TX_DONE, RF_TX_TIMEOUT]
 */

int SX1278Init(SX1278_st_ptr sx1278_ptr)
{
    int i = 0;
    int result = 0;

    for( i = 0; i < sizeof( RadioRegsInit ) / sizeof( RadioRegisters_st ); i++ )
    {
        result = SX1278SetModem(sx1278_ptr, RadioRegsInit[i].modem);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, RadioRegsInit[i].addr, RadioRegsInit[i].value);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    
    // Initialize LoRa registers structure
    result = SX1278SetModem(sx1278_ptr, MODEM_LORA);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278Reset(SX1278_st_ptr sx1278_ptr)
{
    //SX1278SetReset( RADIO_RESET_ON );
    
    // Wait 1ms
    mdelay(1);    

    //SX1278SetReset( RADIO_RESET_OFF );
    
    // Wait 6ms
    mdelay(6);
  
    return 0;
}

/*!
 * Performs the Rx chain calibration for LF and HF bands
 * \remark Must be called just after the reset so all registers are at their
 *         default values
 */
int SX1278RxChainCalibration(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t regval0 = 0, regval1 = 0, regval2 = 0;
    uint8_t regPaConfigInitVal = 0;
    uint32_t initialFreq = 0;
    uint64_t temp = 0;

    // Save context
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_PACONFIG, &regPaConfigInitVal);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_FRFMSB, &regval0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_FRFMID, &regval1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_FRFLSB, &regval2);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    temp = (((uint32_t)regval0 << 16) | ((uint32_t)regval1 << 8) | (uint32_t)regval2) * FREQ_STEP;

    do_div(temp, 100000000);

    initialFreq = (uint32_t)temp;

    // Cut the PA just in case, RFO output, power = -1 dBm
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_PACONFIG, 0x00);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    // Launch Rx chain calibration for LF band
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, (regval0 & RF_IMAGECAL_IMAGECAL_MASK)|RF_IMAGECAL_IMAGECAL_START);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    while((regval0&RF_IMAGECAL_IMAGECAL_RUNNING) == RF_IMAGECAL_IMAGECAL_RUNNING)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    // Sets a Frequency in HF band
    result = SX1278LoRaSetRFFrequency(sx1278_ptr, 868000000);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    // Launch Rx chain calibration for HF band
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, (regval0 &RF_IMAGECAL_IMAGECAL_MASK)|RF_IMAGECAL_IMAGECAL_START);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    while((regval0&RF_IMAGECAL_IMAGECAL_RUNNING) == RF_IMAGECAL_IMAGECAL_RUNNING)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_IMAGECAL, &regval0);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    // Restore context
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_PACONFIG, regPaConfigInitVal);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetRFFrequency(sx1278_ptr, initialFreq);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278SetModem(SX1278_st_ptr sx1278_ptr, RadioModems_en modem)
{
    int result = 0;
    uint8_t regval = 0;
    RadioModems_en curmodem = MODEM_FSK;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if((regval & RFLR_OPMODE_LONGRANGEMODE_ON ) != 0)
    {
        curmodem = MODEM_LORA;
    }
    else
    {
        curmodem = MODEM_FSK;
    }

    if(curmodem == modem)
    {
        goto ERR_EXIT;
    }

    switch(modem)
    {
    default:
    case MODEM_FSK:
        result = SX1278SetOpMode(sx1278_ptr, RFLR_OPMODE_SLEEP);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, (regval&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_OFF);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, 0x00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING2, 0x30); // DIO5=ModeReady
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        break;
    case MODEM_LORA:
        result = SX1278SetOpMode(sx1278_ptr, RFLR_OPMODE_SLEEP);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, (regval&RFLR_OPMODE_LONGRANGEMODE_MASK)|RFLR_OPMODE_LONGRANGEMODE_ON);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, 0x00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING2, 0x00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        break;
    }

ERR_EXIT:

    return result;
}


int SX1278SetLoRaOn(SX1278_st_ptr sx1278_ptr, bool enable)
{
    int result = 0;
    uint8_t RegDioMapping = 0;
    RadioModems_en LoRaOnState = 0;
    uint8_t RegOpMode = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaGetModem(sx1278_ptr, &LoRaOnState);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(LoRaOnState == enable)
    {
        goto ERR_EXIT;
    }
     
    if(enable)
    {
        result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_SLEEP);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, &RegOpMode);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        RegOpMode = ( RegOpMode & RFLR_OPMODE_LONGRANGEMODE_MASK ) | RFLR_OPMODE_LONGRANGEMODE_ON;
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, RegOpMode);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
 
        result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_STANDBY);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

                                  // RxDone               RxTimeout                   FhssChangeChannel           CadDone
        RegDioMapping = RFLR_DIOMAPPING1_DIO0_00 | RFLR_DIOMAPPING1_DIO1_00 | RFLR_DIOMAPPING1_DIO2_00 | RFLR_DIOMAPPING1_DIO3_00;
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DIOMAPPING1, RegDioMapping);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
                                 // CadDetected          ModeReady
        RegDioMapping = RFLR_DIOMAPPING2_DIO4_00 | RFLR_DIOMAPPING2_DIO5_00;
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DIOMAPPING2, RegDioMapping);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_SLEEP);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, &RegOpMode);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        RegOpMode = ( RegOpMode & RFLR_OPMODE_LONGRANGEMODE_MASK ) | RFLR_OPMODE_LONGRANGEMODE_OFF;
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_OPMODE, RegOpMode);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_STANDBY);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

ERR_EXIT:

    return result;
}

int SX1278GetLoRaOn(SX1278_st_ptr sx1278_ptr, bool *LoRaOn)
{
    int result = 0;

    if((NULL == sx1278_ptr) || (NULL == LoRaOn))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
ERR_EXIT:    
    
    return result;
    //return LoRaOn;
}

int SX1278SetOpMode(SX1278_st_ptr sx1278_ptr, uint8_t opMode )
{
    return SX1278LoRaSetOpMode(sx1278_ptr, opMode);        
}

int SX1278GetOpMode(SX1278_st_ptr sx1278_ptr, uint8_t *OpMode)
{
    return SX1278LoRaGetOpMode(sx1278_ptr, OpMode);       
}

int SX1278ReadRssi(SX1278_st_ptr sx1278_ptr, uint32_t freq, int8_t *rssi)
{
    return SX1278LoRaReadRssi(sx1278_ptr, freq, rssi);
}

int SX1278ReadRxGain(SX1278_st_ptr sx1278_ptr, uint8_t *RxGain)
{
    return SX1278LoRaReadRxGain(sx1278_ptr, RxGain);
}

int SX1278GetPacketRxGain(SX1278_st_ptr sx1278_ptr, uint8_t *PacketRxGain)
{
    //return SX1278LoRaGetPacketRxGain(sx1278_ptr, PacketRxGain);
    return 0;
}

int SX1278GetPacketSnr(SX1278_st_ptr sx1278_ptr, int8_t *PacketSnr)
{
    //return SX1278LoRaGetPacketSnr(sx1278_ptr, PacketSnr);
    return 0;
}

int SX1278GetPacketRssi(SX1278_st_ptr sx1278_ptr, int8_t *PacketRssi)
{
    //return SX1278LoRaGetPacketRssi(sx1278_ptr, PacketRssi);
    return 0;
}

int SX1278GetPacketAfc(SX1278_st_ptr sx1278_ptr, uint32_t *PacketAfc)
{
#if 0
    if( LoRaOn == false )
    {
        return SX1278FskGetPacketAfc(  );
    }
    else
    {
         while( 1 )
         {
             // Useless in LoRa mode
             // Block program here
         }
    }
#endif
    return 0;
}

int SX1278SetRxConfig(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t regval = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    // set the Rx RF settings 
    result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetSignalBandwidth(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.SignalBw);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetErrorCoding(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.ErrorCoding);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetImplicitHeaderOn(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.ImplicitHeaderOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetSpreadingFactor(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.SpreadingFactor); // SF6 only operates in implicit header mode.
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetPacketCrcOn(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.CrcOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(((sx1278_ptr->cfg.rx_cfg.SignalBw == 7) && ((sx1278_ptr->cfg.rx_cfg.SpreadingFactor == 11) || (sx1278_ptr->cfg.rx_cfg.SpreadingFactor == 12))) ||
       ((sx1278_ptr->cfg.rx_cfg.SignalBw == 8) && (sx1278_ptr->cfg.rx_cfg.SpreadingFactor == 12)))
    {
        result = SX1278LoRaSetLowDatarateOptimize(sx1278_ptr, true);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278LoRaSetLowDatarateOptimize(sx1278_ptr, false);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    result = SX1278LoRaSetSymbTimeout(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RxPacketTimeout);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetPreambleLength(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.PreambleLen);
    if(result < 0)
    {
        goto ERR_EXIT;
    }    
    
    result = SX1278LoRaSetPayloadLength(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.PayloadLength);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if(sx1278_ptr->cfg.rx_cfg.FreqHopOn)
    {
        result = SX1278LoRaSetFreqHopOn(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.FreqHopOn);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278LoRaSetHopPeriod(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.HopPeriod);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    if((sx1278_ptr->cfg.rx_cfg.SignalBw == 9)&&(sx1278_ptr->cfg.rx_cfg.RFFrequency > RF_MID_BAND_THRESH))
    {
        // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST36, 0x02);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST3A, 0x64);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else if(sx1278_ptr->cfg.rx_cfg.SignalBw == 9)
    {
        // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST36, 0x02);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST3A, 0x7F);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        // ERRATA 2.1 - Sensitivity Optimization with a 500 kHz Bandwidth
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST3A, 0x03);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    if(sx1278_ptr->cfg.rx_cfg.ErrorCoding == 6)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, (regval&RFLR_DETECTIONOPTIMIZE_MASK)|RFLR_DETECTIONOPTIMIZE_SF6);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTIONTHRESHOLD, RFLR_DETECTIONTHRESH_SF6);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
    }
    else
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }   
    
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, (regval&RFLR_DETECTIONOPTIMIZE_MASK)|RFLR_DETECTIONOPTIMIZE_SF7_TO_SF12);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTIONTHRESHOLD, RFLR_DETECTIONTHRESH_SF7_TO_SF12);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }
    
ERR_EXIT:

    return result;
}

int SX1278SetTxConfig(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t regval = 0;   
 
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278SetModem(sx1278_ptr, MODEM_LORA);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278SetRfTxPower(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.RFFrequency, sx1278_ptr->cfg.tx_cfg.Power);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    // set the Rx RF settings 
    result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.RFFrequency);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(sx1278_ptr->cfg.tx_cfg.FreqHopOn)
    {
        result = SX1278LoRaSetFreqHopOn(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.FreqHopOn);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278LoRaSetHopPeriod(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.HopPeriod);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    result = SX1278LoRaSetSignalBandwidth(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.SignalBw);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetErrorCoding(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.ErrorCoding);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetImplicitHeaderOn(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.ImplicitHeaderOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetSpreadingFactor(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.SpreadingFactor); // SF6 only operates in implicit header mode.
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetPacketCrcOn(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.CrcOn);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    

    if(((sx1278_ptr->cfg.tx_cfg.SignalBw == 7) && ((sx1278_ptr->cfg.tx_cfg.SpreadingFactor == 11) || (sx1278_ptr->cfg.tx_cfg.SpreadingFactor == 12))) ||
       ((sx1278_ptr->cfg.tx_cfg.SignalBw == 8) && (sx1278_ptr->cfg.tx_cfg.SpreadingFactor == 12)))
    {
        result = SX1278LoRaSetLowDatarateOptimize(sx1278_ptr, true);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278LoRaSetLowDatarateOptimize(sx1278_ptr, false);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    result = SX1278LoRaSetSymbTimeout(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.TxPacketTimeout);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result = SX1278LoRaSetPreambleLength(sx1278_ptr, sx1278_ptr->cfg.tx_cfg.PreambleLen);
    if(result < 0)
    {
        goto ERR_EXIT;
    }    
    
    if(sx1278_ptr->cfg.tx_cfg.SpreadingFactor == 6)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE,(regval&RFLR_DETECTIONOPTIMIZE_MASK)|RFLR_DETECTIONOPTIMIZE_SF6);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTIONTHRESHOLD, RFLR_DETECTIONTHRESH_SF6);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, (regval&RFLR_DETECTIONOPTIMIZE_MASK)|RFLR_DETECTIONOPTIMIZE_SF7_TO_SF12);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTIONTHRESHOLD, RFLR_DETECTIONTHRESH_SF7_TO_SF12);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

ERR_EXIT:

    return result;

}

int SX1278StartRx(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t regval = 0;
    
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    if(sx1278_ptr->cfg.rx_cfg.IqInverted == true )
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, ((regval&RFLR_INVERTIQ_TX_MASK&RFLR_INVERTIQ_RX_MASK)|RFLR_INVERTIQ_RX_ON|RFLR_INVERTIQ_TX_OFF));
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_ON );
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }
    else
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, ((regval&RFLR_INVERTIQ_TX_MASK&RFLR_INVERTIQ_RX_MASK )|RFLR_INVERTIQ_RX_OFF|RFLR_INVERTIQ_TX_OFF ));
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_OFF);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }    

    // ERRATA 2.3 - Receiver Spurious Reception of a LoRa Signal
    if(sx1278_ptr->cfg.rx_cfg.SignalBw < 9)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, (regval&0x7F));
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST30, 0x00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        switch(sx1278_ptr->cfg.rx_cfg.SignalBw)
        {
        case 0://7.8KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x48);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 7810);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 1://10.4KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x44);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 10420);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 2://15.6KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x44);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 15620);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 3://20.8KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x44);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 20830);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 4://31.2KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x44);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 31250);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 5://41.4KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x44);
            if(result < 0)
            {
                goto ERR_EXIT;
            }

            result = SX1278LoRaSetRFFrequency(sx1278_ptr, sx1278_ptr->cfg.rx_cfg.RFFrequency + 41670);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break; 
        case 6://62.5KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x40);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 7://125KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x40);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;
        case 8://250KHz
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_TEST2F, 0x40);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            break;            
        }
    }else{
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DETECTOPTIMIZE, (regval & 0x80));
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }

    if(sx1278_ptr->cfg.rx_cfg.FreqHopOn == true )
    {
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGSMASK, //RFLR_IRQFLAGS_RXTIMEOUT |
                                                      //RFLR_IRQFLAGS_RXDONE |
                                                      //RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                      RFLR_IRQFLAGS_VALIDHEADER |
                                                      RFLR_IRQFLAGS_TXDONE |
                                                      RFLR_IRQFLAGS_CADDONE |
                                                      //RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                      RFLR_IRQFLAGS_CADDETECTED );
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        // DIO0=RxDone, DIO2=FhssChangeChannel
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, (regval&RFLR_DIOMAPPING1_DIO0_MASK&RFLR_DIOMAPPING1_DIO2_MASK) | RFLR_DIOMAPPING1_DIO0_00 | RFLR_DIOMAPPING1_DIO2_00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGSMASK, //RFLR_IRQFLAGS_RXTIMEOUT |
                                                      //RFLR_IRQFLAGS_RXDONE |
                                                      //RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                      RFLR_IRQFLAGS_VALIDHEADER |
                                                      RFLR_IRQFLAGS_TXDONE |
                                                      RFLR_IRQFLAGS_CADDONE |
                                                      RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                      RFLR_IRQFLAGS_CADDETECTED );
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        // DIO0=RxDone
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, (regval&RFLR_DIOMAPPING1_DIO0_MASK) | RFLR_DIOMAPPING1_DIO0_00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFORXBASEADDR, 0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, 0);
    if(result < 0)
    {
        goto ERR_EXIT;
    } 

ERR_EXIT:

    return result;
}

int SX1278GetRxPacket(SX1278_st_ptr sx1278_ptr, uint8_t *buffer_ptr, uint8_t buffer_len)
{
    int result = 0;
    uint8_t RxPacketSnrEstimate;
    uint8_t RxPacketRssiValue;
    uint8_t RegIrqFlags = 0;
    uint8_t RegPktRssiValue = 0;
    uint8_t RegFifoAddrPtr = 0;
    uint8_t RegFifoRxBaseAddr = 0;
    //SX1278LoRaGetRxPacket( buffer, size );
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, &RegIrqFlags);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if((RegIrqFlags & RFLR_IRQFLAGS_PAYLOADCRCERROR) == RFLR_IRQFLAGS_PAYLOADCRCERROR)
    {
        // Clear Irq
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_PAYLOADCRCERROR );
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        if( sx1278_ptr->cfg.rx_cfg.RxSingleOn == true ) // Rx single mode
        {
            //RFLRState = RFLR_STATE_RX_INIT;
            result = SX1278StartRx(sx1278_ptr);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
        }
        else
        {
            //RFLRState = RFLR_STATE_RX_RUNNING;
        }

        return result;
    }
    
    {
        uint8_t rxSnrEstimate;
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PKTSNRVALUE, &rxSnrEstimate);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        if(rxSnrEstimate & 0x80) // The SNR sign bit is 1
        {
            // Invert and divide by 4
            RxPacketSnrEstimate = ( ( ~rxSnrEstimate + 1 ) & 0xFF ) >> 2;
            RxPacketSnrEstimate = -RxPacketSnrEstimate;
        }
        else
        {
            // Divide by 4
            RxPacketSnrEstimate = ( rxSnrEstimate & 0xFF ) >> 2;
        }
    }
    
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PKTRSSIVALUE, &RegPktRssiValue);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(sx1278_ptr->cfg.rx_cfg.RFFrequency < 860000000)  // LF
    {    
        if(RxPacketSnrEstimate < 0)
        {
            RxPacketRssiValue = RSSI_OFFSET_LF + RegPktRssiValue + RxPacketSnrEstimate;
        }
        else
        {
            RxPacketRssiValue = RSSI_OFFSET_LF + (uint8_t)((uint32_t)10666 * RegPktRssiValue / 10000);
        }
    }
    else                                        // HF
    {    
        if(RxPacketSnrEstimate < 0)
        {
            RxPacketRssiValue = RSSI_OFFSET_HF + RegPktRssiValue + RxPacketSnrEstimate;
        }
        else
        {    
            RxPacketRssiValue = RSSI_OFFSET_HF + (uint8_t)((uint32_t)10666 * RegPktRssiValue / 10000);
        }
    }

    if(sx1278_ptr->cfg.rx_cfg.RxSingleOn == true) // Rx single mode
    {
        RegFifoAddrPtr = RegFifoRxBaseAddr;
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, RegFifoAddrPtr);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        if(sx1278_ptr->cfg.rx_cfg.ImplicitHeaderOn == true)
        {
            result = SX1278_Read_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, buffer_len);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
        }
        else
        {
            uint8_t RegNbRxBytes = 0;
            result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_RXNBBYTES, &RegNbRxBytes);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            result = SX1278_Read_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, RegNbRxBytes);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            result = RegNbRxBytes;
        }
    }
    else // Rx continuous mode
    {
        uint8_t RegFifoRxCurrentAddr = 0;
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFORXCURRENTADDR, &RegFifoRxCurrentAddr);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        if(sx1278_ptr->cfg.rx_cfg.ImplicitHeaderOn == true)
        {            
            RegFifoAddrPtr = RegFifoRxCurrentAddr;
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, RegFifoAddrPtr);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            result = SX1278_Read_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, buffer_len);
            if(result < 0)
            {
                goto ERR_EXIT;
            }            
        }
        else
        {
            uint8_t RegNbRxBytes = 0;
            result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_RXNBBYTES, &RegNbRxBytes);
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            RegFifoAddrPtr = RegFifoRxCurrentAddr;
            result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, RegFifoAddrPtr );
            if(result < 0)
            {
                goto ERR_EXIT;
            }
            
            result = SX1278_Read_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, RegNbRxBytes );
            if(result < 0)
            {
                goto ERR_EXIT;
            }            
        }
    }
    
    if( sx1278_ptr->cfg.rx_cfg.RxSingleOn == true ) // Rx single mode
    {
        //RFLRState = RFLR_STATE_RX_INIT;
    }
    else // Rx continuous mode
    {
        //RFLRState = RFLR_STATE_RX_RUNNING;
    }

ERR_EXIT:

    return result;
}

int SX1278RxFinished(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t RegHopChannel = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    if(sx1278_ptr->cfg.rx_cfg.FreqHopOn == true)
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_HOPCHANNEL, &RegHopChannel);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278LoRaSetRFFrequency(sx1278_ptr, HoppingFrequencies[RegHopChannel & RFLR_HOPCHANNEL_CHANNEL_MASK]);
        if(result < 0)
        {
            goto ERR_EXIT;
        }    
    }
    // Clear Irq
    //SX1278_Write_Reg( REG_LR_IRQFLAGS, RFLR_IRQFLAGS_RXDONE);
ERR_EXIT:

    return result;
}

int SX1278LoRaGetPacketSnrandRssi(SX1278_st_ptr sx1278_ptr, uint32_t freq, int8_t *snr, int16_t *rssi)
{
    int result = 0;
    uint8_t regval = 0;
    int8_t snrval = 0;
    
    if((NULL == sx1278_ptr) || (NULL == snr) || (NULL == rssi))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PKTSNRVALUE, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    snrval = (int8_t)regval;
    if(snrval & 0x80) // The SNR sign bit is 1
    {
        // Invert and divide by 4
        *snr = ( ( ~snrval + 1 ) & 0xFF ) >> 2;
        *snr = -*snr;
    }
    else
    {
        // Divide by 4
        *snr = ( snrval & 0xFF ) >> 2;
    }

    if((NULL == sx1278_ptr) || (NULL == rssi))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_PKTRSSIVALUE, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if( *snr < 0 )
    {
        if( freq > RF_MID_BAND_THRESH )
        {
            *rssi = (int16_t)(RSSI_OFFSET_HF + regval + ( regval >> 4 ) + *snr);
        }
        else
        {
            *rssi = (int16_t)(RSSI_OFFSET_LF + regval + (regval >> 4 ) + *snr);
        }
    }
    else
    {
        if(sx1278_ptr->cfg.tx_cfg.RFFrequency > RF_MID_BAND_THRESH )
        {
            *rssi = RSSI_OFFSET_HF + regval + ( regval >> 4 );
        }
        else
        {
            *rssi = RSSI_OFFSET_LF + regval + ( regval >> 4 );
        }
    }

ERR_EXIT:

    return result;    
}


int SX1278LoRaCheckPayloadCrc(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t irqFlags = 0;
    
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, &irqFlags);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if((irqFlags & RFLR_IRQFLAGS_PAYLOADCRCERROR_MASK) == RFLR_IRQFLAGS_PAYLOADCRCERROR)
    {
        // Clear Irq
        result = SX1278LoRaClearIrq(sx1278_ptr, RFLR_IRQFLAGS_PAYLOADCRCERROR);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        if( sx1278_ptr->cfg.rx_cfg.RxSingleOn == false)
        {
            result = -ECRC;
            goto ERR_EXIT;
        }
    }
    
ERR_EXIT:

    return result;
}

int SX1278LoRaClearIrq(SX1278_st_ptr sx1278_ptr, uint8_t mask)
{
    int result = 0;
    
    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, mask);
 
ERR_EXIT:

    return result;
}

int SX1278StartTx(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    // must be sure in standby mode before this, I think we need mutex lock
    result = SX1278SetOpMode(sx1278_ptr, RF_OPMODE_TRANSMITTER);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
        
ERR_EXIT:

    return result;
}

int SX1278SetTxPacket(SX1278_st_ptr sx1278_ptr, uint8_t *buffer_ptr, uint8_t buffer_len )
{
    int result = 0;
    uint8_t regval = 0;

    if((NULL == sx1278_ptr) || (NULL == buffer_ptr))
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    if(sx1278_ptr->cfg.tx_cfg.IqInverted == true )
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, ((regval&RFLR_INVERTIQ_TX_MASK & RFLR_INVERTIQ_RX_MASK)|RFLR_INVERTIQ_RX_OFF|RFLR_INVERTIQ_TX_ON));
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_ON);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ, ((regval&RFLR_INVERTIQ_TX_MASK&RFLR_INVERTIQ_RX_MASK)|RFLR_INVERTIQ_RX_OFF|RFLR_INVERTIQ_TX_OFF));
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_INVERTIQ2, RFLR_INVERTIQ2_OFF);
        if(result < 0)
        {
            goto ERR_EXIT;
        }        
    }
    
    // Initializes the payload size
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_PAYLOADLENGTH, buffer_len);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    // Full buffer used for Tx
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOTXBASEADDR, 0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
        
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_FIFOADDRPTR, 0);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    // FIFO operations can not take place in Sleep mode
    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_OPMODE, &regval);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    if((regval&~RF_OPMODE_MASK) == RF_OPMODE_SLEEP)
    {
        result = SX1278SetOpMode(sx1278_ptr, RF_OPMODE_STANDBY);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        mdelay(1);
    }
    // Write payload buffer
    result = SX1278_Write_FIFO(sx1278_ptr->spi_ptr, buffer_ptr, buffer_len);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    if(sx1278_ptr->cfg.tx_cfg.FreqHopOn == true)
    {
    
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                                      RFLR_IRQFLAGS_RXDONE |
                                                      RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                      RFLR_IRQFLAGS_VALIDHEADER |
                                                      //RFLR_IRQFLAGS_TXDONE |
                                                      RFLR_IRQFLAGS_CADDONE |
                                                      //RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                      RFLR_IRQFLAGS_CADDETECTED );
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        // DIO0=TxDone, DIO2=FhssChangeChannel
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, (regval&RFLR_DIOMAPPING1_DIO0_MASK&RFLR_DIOMAPPING1_DIO2_MASK)|RFLR_DIOMAPPING1_DIO0_01|RFLR_DIOMAPPING1_DIO2_00);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    else
    {
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGSMASK, RFLR_IRQFLAGS_RXTIMEOUT |
                                                      RFLR_IRQFLAGS_RXDONE |
                                                      RFLR_IRQFLAGS_PAYLOADCRCERROR |
                                                      RFLR_IRQFLAGS_VALIDHEADER |
                                                      //RFLR_IRQFLAGS_TXDONE |
                                                      RFLR_IRQFLAGS_CADDONE |
                                                      RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL |
                                                      RFLR_IRQFLAGS_CADDETECTED );
        if(result < 0)
        {
            goto ERR_EXIT;
        }        

        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, &regval);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        // DIO0=TxDone
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_DIOMAPPING1, (regval& RFLR_DIOMAPPING1_DIO0_MASK ) | RFLR_DIOMAPPING1_DIO0_01);
        if(result < 0)
        {
            goto ERR_EXIT;
        }            
    }
    
ERR_EXIT:
    
    return result;
}

int SX1278TxFinished(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_TXDONE);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_STANDBY);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278FhssChangedChannel(SX1278_st_ptr sx1278_ptr, uint8_t *RxGain)
{
    int result = 0;
    uint8_t RegHopChannel = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    //problem
    if( sx1278_ptr->cfg.rx_cfg.FreqHopOn == true )
    {
        result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_HOPCHANNEL, &RegHopChannel);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
        
        result = SX1278LoRaSetRFFrequency(sx1278_ptr, HoppingFrequencies[RegHopChannel & RFLR_HOPCHANNEL_CHANNEL_MASK]);
        if(result < 0)
        {
            goto ERR_EXIT;
        }
    }
    // Clear Irq
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL);
    if(result < 0)
    {
        goto ERR_EXIT;
    }    
    // Debug
    result = SX1278LoRaReadRxGain(sx1278_ptr, RxGain);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
   
ERR_EXIT:

    return result;
}

int SX1278StartCad(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t RegIrqFlagsMask = 0;
    uint8_t RegDioMapping1 = 0;
    //uint8_t RegDioMapping2 = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }
    
    result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_STANDBY);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    RegIrqFlagsMask = RFLR_IRQFLAGS_RXTIMEOUT |
                        RFLR_IRQFLAGS_RXDONE |
                        RFLR_IRQFLAGS_PAYLOADCRCERROR |
                        RFLR_IRQFLAGS_VALIDHEADER |
                        RFLR_IRQFLAGS_TXDONE |
                        //RFLR_IRQFLAGS_CADDONE |
                        RFLR_IRQFLAGS_FHSSCHANGEDCHANNEL; // |
                        //RFLR_IRQFLAGS_CADDETECTED;
    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGSMASK, RegIrqFlagsMask);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

    result =SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_DIOMAPPING1, &RegDioMapping1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
                                // CadDone
    RegDioMapping1 = ((RegDioMapping1 & RFLR_DIOMAPPING1_DIO3_MASK ) | RFLR_DIOMAPPING1_DIO3_00);
                                // CAD Detected              ModeReady
    //RegDioMapping2 = RFLR_DIOMAPPING2_DIO4_00 | RFLR_DIOMAPPING2_DIO5_00;

    result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DIOMAPPING1, RegDioMapping1);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    
    //result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_DIOMAPPING1, RegDioMapping2);
    //if(result < 0)
    //{
    //    goto ERR_EXIT;
    //}

    result = SX1278LoRaSetOpMode(sx1278_ptr, RFLR_OPMODE_CAD);
    if(result < 0)
    {
        goto ERR_EXIT;
    }

ERR_EXIT:

    return result;
}

int SX1278CadDone(SX1278_st_ptr sx1278_ptr)
{
    int result = 0;
    uint8_t RegIrqFlags = 0;

    if(NULL == sx1278_ptr)
    {
        result = -ENOMEM;
        goto ERR_EXIT;
    }

    result = SX1278_Read_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, &RegIrqFlags);
    if(result < 0)
    {
        goto ERR_EXIT;
    }
    printk(KERN_ERR "RegIrqFlags:0x%0x\n", RegIrqFlags); 
    if((RegIrqFlags&RFLR_IRQFLAGS_CADDETECTED) == RFLR_IRQFLAGS_CADDETECTED)
    {
        // Clear Irq
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, (RFLR_IRQFLAGS_CADDETECTED |RFLR_IRQFLAGS_CADDONE));
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = 1;
    }
    else
    {
        // Clear Irq
        result = SX1278_Write_Reg(sx1278_ptr->spi_ptr, REG_LR_IRQFLAGS, RFLR_IRQFLAGS_CADDONE);
        if(result < 0)
        {
            goto ERR_EXIT;
        }

        result = 0;
    }
    
ERR_EXIT:

    return result;
}
int SX1278GetRFState(SX1278_st_ptr sx1278_ptr, uint8_t *RFState)
{
    return SX1278LoRaGetRFState(sx1278_ptr, RFState);
}

int SX1278SetRFState(SX1278_st_ptr sx1278_ptr, uint8_t state)
{
    return SX1278LoRaSetRFState(sx1278_ptr, state);
}

int SX1278Process(SX1278_st_ptr sx1278_ptr)
{
    //return SX1278LoRaProcess( );
    return 0;
}


